<?php
/**
 * Автогенерировано build-tools/generate_pages.py:build_blog_schema_map() —
 * НЕ редактировать вручную. Карта slug-статьи → дата публикации (ISO) и
 * обложка, для JSON-LD BlogPosting (см. remarka_blog_posting_schema).
 */
return array(
	'_modified' => '2026-07-21',
	'posts' => array(
		'perche-il-sito-non-converte' => array( 'date' => '2026-07-21', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/nonconverte-cover.svg' ),
		'why-your-website-doesnt-convert' => array( 'date' => '2026-07-21', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/nonconverte-cover.svg' ),
		'landing-page-che-converte' => array( 'date' => '2026-07-21', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/landing-cover.svg' ),
		'landing-page-that-converts' => array( 'date' => '2026-07-21', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/landing-cover.svg' ),
		'recensioni-riprova-sociale-onesta' => array( 'date' => '2026-07-20', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/recensioni-cover.svg' ),
		'reviews-social-proof-done-right' => array( 'date' => '2026-07-20', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/recensioni-cover.svg' ),
		'whatsapp-business-pmi' => array( 'date' => '2026-07-20', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/whatsapp-cover.svg' ),
		'whatsapp-business-for-smes' => array( 'date' => '2026-07-20', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/whatsapp-cover.svg' ),
		'copywriting-sito-web-prima-del-design' => array( 'date' => '2026-07-20', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/copy-cover.svg' ),
		'website-copywriting-before-design' => array( 'date' => '2026-07-20', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/copy-cover.svg' ),
		'sito-quattro-lingue-costi-tempi' => array( 'date' => '2026-05-05', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/quattro-cover.svg' ),
		'website-four-languages-costs' => array( 'date' => '2026-05-05', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/quattro-cover.svg' ),
		'sajt-na-4-jazykah' => array( 'date' => '2026-05-05', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/quattro-cover.svg' ),
		'cookie-banner-checklist-garante-2026' => array( 'date' => '2026-04-08', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/cookie-cover.svg' ),
		'cookie-banner-compliance-italy-2026' => array( 'date' => '2026-04-08', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/cookie-cover.svg' ),
		'cookie-banner-trebovanija-2026' => array( 'date' => '2026-04-08', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/cookie-cover.svg' ),
		'migrare-wordpress-senza-perdere-seo' => array( 'date' => '2026-03-17', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/migrare-cover.svg' ),
		'migrate-wordpress-without-losing-seo' => array( 'date' => '2026-03-17', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/migrare-cover.svg' ),
		'migracija-wordpress-bez-poteri-seo' => array( 'date' => '2026-03-17', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/migrare-cover.svg' ),
		'pwa-per-pmi-quando-app-non-serve' => array( 'date' => '2026-02-24', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/pwa-cover.svg' ),
		'pwa-for-smbs' => array( 'date' => '2026-02-24', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/pwa-cover.svg' ),
		'pwa-dlja-biznesa' => array( 'date' => '2026-02-24', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/pwa-cover.svg' ),
		'quanto-costa-sito-aziendale-italia' => array( 'date' => '2026-02-03', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/costo-sito-cover.svg' ),
		'business-website-cost-italy' => array( 'date' => '2026-02-03', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/costo-sito-cover.svg' ),
		'skolko-stoit-sajt-v-italii' => array( 'date' => '2026-02-03', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/costo-sito-cover.svg' ),
		'core-web-vitals-2026' => array( 'date' => '2026-01-12', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/cwv-cover.svg' ),
		'quanto-costa-ecommerce-italia' => array( 'date' => '2026-07-13', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/costo-ecom-cover.svg' ),
		'ecommerce-cost-italy-2026' => array( 'date' => '2026-07-13', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/costo-ecom-cover.svg' ),
		'skolko-stoit-internet-magazin' => array( 'date' => '2026-07-13', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/costo-ecom-cover.svg' ),
		'sito-lento-cause-costi' => array( 'date' => '2026-07-13', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/sito-lento-cover.svg' ),
		'slow-website-causes-fixes' => array( 'date' => '2026-07-13', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/sito-lento-cover.svg' ),
		'medlennyj-sajt-prichiny' => array( 'date' => '2026-07-13', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/sito-lento-cover.svg' ),
		'european-accessibility-act-ecommerce' => array( 'date' => '2026-07-15', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/eaa-cover.svg' ),
		'eaa-ecommerce-risks' => array( 'date' => '2026-07-15', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/eaa-cover.svg' ),
		'llms-txt-cos-e' => array( 'date' => '2026-07-15', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/llmstxt-cover.svg' ),
		'llms-txt-explained' => array( 'date' => '2026-07-15', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/llmstxt-cover.svg' ),
		'farsi-trovare-da-chatgpt-geo' => array( 'date' => '2026-07-15', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/geo-cover.svg' ),
		'get-cited-by-chatgpt-geo' => array( 'date' => '2026-07-15', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/geo-cover.svg' ),
		'check-up-sito-web-7-misure' => array( 'date' => '2026-07-15', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/checkup-cover.svg' ),
		'website-checkup-7-metrics' => array( 'date' => '2026-07-15', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/checkup-cover.svg' ),
		'eeat-come-google-giudica-credibilita' => array( 'date' => '2026-07-15', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/eeat-cover.svg' ),
		'eeat-how-google-judges-credibility' => array( 'date' => '2026-07-15', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/eeat-cover.svg' ),
		'preventivo-sito-web-come-leggerlo' => array( 'date' => '2026-07-16', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/preventivo-cover.svg' ),
		'website-quote-how-to-read-it' => array( 'date' => '2026-07-16', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/preventivo-cover.svg' ),
		'sito-web-in-3-settimane' => array( 'date' => '2026-07-16', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/tresett-cover.svg' ),
		'website-in-3-weeks' => array( 'date' => '2026-07-16', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/tresett-cover.svg' ),
		'restyling-o-sito-nuovo-5-domande' => array( 'date' => '2026-07-16', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/restyling-cover.svg' ),
		'redesign-or-new-website-5-questions' => array( 'date' => '2026-07-16', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/restyling-cover.svg' ),
		'impatto-ambientale-sito-web' => array( 'date' => '2026-07-16', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/impatto-cover.svg' ),
		'website-environmental-impact' => array( 'date' => '2026-07-16', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/impatto-cover.svg' ),
		'dichiarazione-di-accessibilita-guida-2026' => array( 'date' => '2026-07-16', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/dichiarazione-cover.svg' ),
		'accessibility-statement-guide-2026' => array( 'date' => '2026-07-16', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/dichiarazione-cover.svg' ),
		'telegram-mini-app-business' => array( 'date' => '2026-07-17', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/tgminiapp-cover.svg' ),
		'telegram-mini-app-for-business' => array( 'date' => '2026-07-17', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/tgminiapp-cover.svg' ),
		'gestionale-su-misura-vs-excel' => array( 'date' => '2026-07-17', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/gestionale-cover.svg' ),
		'custom-management-software-vs-excel' => array( 'date' => '2026-07-17', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/gestionale-cover.svg' ),
		'dati-strutturati-schema-org' => array( 'date' => '2026-07-17', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/schema-cover.svg' ),
		'schema-org-structured-data-for-smes' => array( 'date' => '2026-07-17', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/schema-cover.svg' ),
		'gamification-b2b' => array( 'date' => '2026-07-17', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/gamification-cover.svg' ),
		'gamification-in-b2b' => array( 'date' => '2026-07-17', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/gamification-cover.svg' ),
		'hosting-sito-web-italia' => array( 'date' => '2026-07-17', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/hosting-cover.svg' ),
		'website-hosting-italy-vs-cloud' => array( 'date' => '2026-07-17', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/hosting-cover.svg' ),
		'seo-locale-milano' => array( 'date' => '2026-07-18', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/seolocale-cover.svg' ),
		'local-seo-milan' => array( 'date' => '2026-07-18', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/seolocale-cover.svg' ),
		'google-business-profile-guida' => array( 'date' => '2026-07-18', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/gbp-cover.svg' ),
		'google-business-profile-guide' => array( 'date' => '2026-07-18', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/gbp-cover.svg' ),
		'hreflang-sito-multilingue' => array( 'date' => '2026-07-18', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/hreflang-cover.svg' ),
		'hreflang-multilingual-website' => array( 'date' => '2026-07-18', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/hreflang-cover.svg' ),
		'sito-per-export' => array( 'date' => '2026-07-18', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/export-cover.svg' ),
		'website-for-export' => array( 'date' => '2026-07-18', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/export-cover.svg' ),
		'manutenzione-wordpress' => array( 'date' => '2026-07-18', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/manutenzione-cover.svg' ),
		'wordpress-maintenance' => array( 'date' => '2026-07-18', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/manutenzione-cover.svg' ),
		'area-clienti-agenzia-web' => array( 'date' => '2026-07-19', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/areaclienti-cover.svg' ),
		'web-agency-client-portal' => array( 'date' => '2026-07-19', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/areaclienti-cover.svg' ),
		'monitoraggio-sito-dopo-lancio' => array( 'date' => '2026-07-19', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/monitoraggio-cover.svg' ),
		'website-monitoring-after-launch' => array( 'date' => '2026-07-19', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/monitoraggio-cover.svg' ),
		'sajt-dlya-vyhoda-na-rynok-italii' => array( 'date' => '2026-07-19', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/batch5-mercato-cover.svg' ),
		'seo-v-italii-po-russki' => array( 'date' => '2026-07-19', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/batch5-seo-cover.svg' ),
		'gdpr-dlya-russkoyazychnogo-biznesa-v-es' => array( 'date' => '2026-07-19', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/batch5-gdpr-cover.svg' ),
		'perevesti-ili-lokalizovat-sajt' => array( 'date' => '2026-07-19', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/batch5-loc-cover.svg' ),
		'cena-sajta-v-italii' => array( 'date' => '2026-07-19', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/batch5-cena-cover.svg' ),
		'telegram-prilozhenie-dlya-biznesa-v-evrope' => array( 'date' => '2026-07-20', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/batch6-tg-cover.svg' ),
		'kak-proverit-veb-studiyu' => array( 'date' => '2026-07-20', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/batch6-fiducia-cover.svg' ),
		'zakon-o-dostupnosti-sajtov' => array( 'date' => '2026-07-20', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/batch6-eaa-cover.svg' ),
		'sajt-v-chatgpt' => array( 'date' => '2026-07-20', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/batch6-chatgpt-cover.svg' ),
		'russkoyazychnaya-auditoriya-v-evrope' => array( 'date' => '2026-07-20', 'image' => '/wp-content/themes/remarka-studio/assets/img/blog/batch6-rus-cover.svg' ),
	),
);
