"""Контент студии — единый источник для генератора WP-страниц.
Тот же корпус текста, что был в Astro-прототипе (services.ts/cases.ts/
tools.ts/cities.ts/blog.ts), перенесён без изменений смысла — редактура
и адаптация под WordPress выполняются один раз, здесь.
"""

SERVICES = [
    dict(
        slug='siti-aziendali', title='Siti aziendali',
        breadcrumb='Servizio / Siti aziendali',
        hero_sub='Struttura chiara e caricamento sotto il secondo per chi vive di richieste di preventivo.',
        hero_stat_value='1,1 s', hero_stat_label='tempo di caricamento medio consegnato',
        per_chi=[
            'Aziende B2B che ricevono richieste di preventivo dal sito',
            'PMI con un sito datato che carica in 4–6 secondi',
            'Chi ha bisogno di gestire contenuti senza uno sviluppatore',
        ],
        include=[
            'Fino a 15 pagine su misura', 'CMS per aggiornare testi e immagini in autonomia',
            'Modulo contatti con notifica email e WhatsApp',
            'SEO tecnica: dati strutturati, sitemap, meta tag',
            'Ottimizzazione immagini e caricamento differito',
            'Certificato SSL e hosting incluso il primo anno',
            "Formazione all’uso del CMS (1 sessione)", 'PageSpeed 90+ garantito da contratto',
        ],
        mini_caso=dict(cliente='TecnoIdraulica', prima=29, dopo=94,
                        testo='Il sito precedente impiegava 5,8 secondi a caricare su mobile. Dopo il restyling tecnico, le richieste di preventivo sono più che raddoppiate in tre mesi.'),
        prezzo_range='€ 3.900–5.800',
        prezzo_note=['Numero di pagine e sezioni personalizzate', "Lingue aggiuntive oltre l’italiano",
                     'Integrazioni (CRM, newsletter, prenotazioni)'],
        faq=[
            ('Posso aggiornare i contenuti da solo?', 'Sì, il CMS incluso permette di modificare testi, immagini e aggiungere pagine senza competenze tecniche.'),
            ('Cosa succede al dominio attuale?', 'Gestiamo noi la migrazione DNS, senza interruzioni di servizio o perdita di email.'),
            ('Il sito funziona anche su mobile?', 'Sì, ogni sito è progettato mobile-first e testato su Lighthouse prima della consegna.'),
        ],
    ),
    dict(
        slug='e-commerce', title='E-commerce',
        breadcrumb='Servizio / E-commerce',
        hero_sub='Cataloghi veloci e checkout senza attriti, con fatturazione elettronica integrata.',
        hero_stat_value='1,4 s', hero_stat_label='tempo di caricamento medio consegnato',
        per_chi=[
            'Attività che vendono online ma perdono clienti nel checkout',
            'Negozi fisici pronti ad aprire un canale e-commerce',
            'Chi ha bisogno di fatturazione elettronica automatica',
        ],
        include=[
            'Catalogo prodotti illimitato con varianti', 'Checkout in un solo passaggio',
            'Pagamenti con carta, PayPal e bonifico', 'Fatturazione elettronica via SDI integrata',
            'Gestione magazzino e spedizioni', 'SEO tecnica per le pagine prodotto',
            "Formazione all’uso del pannello ordini", 'PageSpeed 90+ garantito da contratto',
        ],
        mini_caso=dict(cliente='Pasticceria Volta', prima=22, dopo=91,
                        testo='Il vecchio store impiegava oltre 6 secondi a caricare le pagine prodotto. Con il nuovo catalogo veloce, il tasso di abbandono carrello è sceso del 34%.'),
        prezzo_range='€ 7.500–14.000',
        prezzo_note=['Numero di prodotti e varianti', 'Integrazioni con corrieri e magazzino',
                     'Metodi di pagamento aggiuntivi'],
        faq=[
            ('Gestite anche la fatturazione elettronica?', 'Sì, ogni ordine genera automaticamente una fattura elettronica conforme SDI.'),
            ("Posso vendere anche all’estero?", 'Sì, il catalogo supporta più lingue e più valute su richiesta.'),
            ('Quanto costa mantenere il negozio online?', 'Hosting e assistenza sono inclusi nei primi 12 mesi; dopo, un canone annuale contenuto copre aggiornamenti e sicurezza.'),
        ],
    ),
    dict(
        slug='siti-pwa', title='Siti progressivi PWA',
        breadcrumb='Servizio / Siti progressivi PWA',
        hero_sub="Un sito che si comporta come un’app: installabile, funziona anche offline, apre all’istante.",
        hero_stat_value='0,9 s', hero_stat_label='tempo di caricamento medio consegnato',
        per_chi=[
            'Attività con clienti che tornano spesso sul sito',
            "Chi vuole un’app senza i costi di App Store e Play Store",
            'Servizi che devono funzionare anche con connessione debole',
        ],
        include=[
            'Installabile su smartphone come un’app', 'Funziona offline per le pagine già visitate',
            'Notifiche push opzionali', 'Caricamento istantaneo dopo la prima visita',
            'Service worker configurato e testato', 'SEO tecnica completa',
            "Formazione all’uso del pannello contenuti", 'PageSpeed 90+ garantito da contratto',
        ],
        mini_caso=dict(cliente='Studio Fontana', prima=31, dopo=96,
                        testo="Trasformato in PWA, il sito si apre ora in meno di un secondo anche per i clienti che lo hanno già visitato, con un incremento del 63% nelle richieste ripetute."),
        prezzo_range='€ 4.900–7.200',
        prezzo_note=['Funzionalità offline richieste', 'Notifiche push e integrazioni native',
                     'Numero di pagine e sezioni'],
        faq=[
            ('Serve pubblicarlo sugli store?', 'No, si installa direttamente dal browser: nessuna revisione Apple o Google necessaria.'),
            ('Funziona su tutti gli smartphone?', 'Sì, è compatibile con iOS e Android tramite qualsiasi browser moderno.'),
            ('Posso passare da un sito esistente a una PWA?', 'Sì, è un percorso di restyling tecnico che manteniamo trasparente per i motori di ricerca.'),
        ],
    ),
    dict(
        slug='restyling-migrazione', title='Restyling e migrazione',
        breadcrumb='Servizio / Restyling e migrazione',
        hero_sub='Il vostro sito attuale, ricostruito: stessi contenuti, il triplo della velocità.',
        hero_stat_value='1,2 s', hero_stat_label='tempo di caricamento medio consegnato',
        per_chi=[
            'Chi ha un sito lento ma non vuole perdere posizionamento SEO',
            'Attività con contenuti validi ma tecnologia datata',
            'Chi ha ricevuto un preventivo di rifacimento completo troppo costoso',
        ],
        include=[
            'Audit tecnico del sito attuale', 'Migrazione dei contenuti esistenti',
            'Redirect 301 per mantenere il posizionamento SEO', 'Nuova base tecnica performante',
            'Ottimizzazione immagini e font', 'Test comparativo prima/dopo su PageSpeed',
            "Formazione all’uso del nuovo CMS", 'PageSpeed 90+ garantito da contratto',
        ],
        mini_caso=dict(cliente='Officine Riva', prima=27, dopo=93,
                        testo="Stessi contenuti, stessa struttura di navigazione: solo la base tecnica è cambiata. Il posizionamento su Google è rimasto invariato, la velocità è triplicata."),
        prezzo_range='€ 2.900–4.800',
        prezzo_note=['Numero di pagine da migrare', 'Complessità delle integrazioni esistenti',
                     'Necessità di redesign grafico'],
        faq=[
            ('Perdo il posizionamento su Google?', 'No, impostiamo redirect 301 corretti per ogni URL esistente prima di andare online.'),
            ('Devo riscrivere i contenuti?', 'No, il restyling tecnico mantiene i contenuti esistenti; li aggiorniamo solo su richiesta.'),
            ('Quanto dura la migrazione?', 'In media 2–4 settimane, con un ambiente di prova visibile fin dalla prima settimana.'),
        ],
    ),
    dict(
        slug='seo-tecnica', title='SEO tecnica',
        breadcrumb='Servizio / SEO tecnica',
        hero_sub='Struttura, dati e Core Web Vitals a posto prima ancora di scrivere i contenuti.',
        hero_stat_value='90+', hero_stat_label='punteggio Core Web Vitals garantito',
        per_chi=[
            'Siti con buoni contenuti ma scarsa visibilità su Google',
            'Chi ha già investito in copywriting senza risultati',
            'Attività che competono in mercati locali affollati',
        ],
        include=[
            'Audit tecnico SEO completo', 'Dati strutturati (schema.org) per ogni tipo di pagina',
            'Ottimizzazione Core Web Vitals', 'Sitemap XML e file robots ottimizzati',
            'Struttura URL e gerarchia dei contenuti', 'Ottimizzazione meta title e description',
            'Report mensile di posizionamento', 'PageSpeed 90+ garantito da contratto',
        ],
        mini_caso=dict(cliente='B&B Il Cortile', prima=33, dopo=95,
                        testo='Con la SEO tecnica sistemata, il B&B è passato dalla terza alla prima pagina di Google per le ricerche locali principali in otto settimane.'),
        prezzo_range='€ 1.800–3.500',
        prezzo_note=['Numero di pagine da ottimizzare', 'Presenza di contenuti multilingua',
                     'Storico tecnico da correggere'],
        faq=[
            ('In quanto tempo si vedono risultati?', 'I miglioramenti tecnici sono immediati; il posizionamento su Google richiede in media 6–10 settimane.'),
            ('Scrivete anche i contenuti?', 'Il servizio è tecnico; per la scrittura dei testi lavoriamo con copywriter partner su richiesta.'),
            ('Fate SEO locale?', 'Sì, includiamo l’ottimizzazione della scheda Google Business Profile quando pertinente.'),
        ],
    ),
    dict(
        slug='siti-multilingue', title='Siti multilingue',
        breadcrumb='Servizio / Siti multilingue',
        hero_sub='Quattro lingue tradotte da madrelingua: dal 2001 è il mestiere del gruppo Remarka.',
        hero_stat_value='4', hero_stat_label='lingue native disponibili',
        per_chi=[
            'Aziende che esportano o accolgono clienti stranieri',
            'Attività turistiche con visitatori internazionali',
            'Chi ha usato finora traduzioni automatiche poco professionali',
        ],
        include=[
            'Traduzione professionale da madrelingua (non plugin)',
            'Fino a 4 lingue: italiano, inglese, tedesco, francese', 'Selettore lingua persistente',
            'SEO multilingue con hreflang corretti', 'Contenuti localizzati, non solo tradotti',
            'Revisione linguistica da parte del gruppo Remarka',
            "Formazione all’uso del CMS multilingue", 'PageSpeed 90+ garantito da contratto',
        ],
        mini_caso=dict(cliente='Cantina Serralta', prima=40, dopo=92,
                        testo="Con il sito tradotto in tedesco e inglese da madrelingua, le richieste dall’estero sono passate dal 5% al 22% del totale in un anno."),
        prezzo_range='€ 3.200–5.500',
        prezzo_note=['Numero di lingue aggiuntive', 'Volume di contenuti da tradurre',
                     'Necessità di revisione periodica'],
        faq=[
            ('Le traduzioni sono automatiche?', 'No, sono realizzate da traduttori madrelingua del gruppo Remarka, non da plugin automatici.'),
            ('Posso aggiungere una lingua in futuro?', 'Sì, la struttura multilingue è predisposta per aggiungere nuove lingue senza rifare il sito.'),
            ('La SEO funziona in tutte le lingue?', 'Sì, ogni lingua ha URL e tag hreflang dedicati per essere indicizzata correttamente da Google.'),
        ],
    ),
]

CASES = [
    dict(
        slug='arredamenti-colombo', cliente='Arredamenti Colombo',
        titolo='Da 34 a 96 in sei settimane, con il 41% di richieste in più',
        settore='Arredamento su misura', citta='Lissone (MB)', intervento='Restyling e migrazione',
        anno='2025', key_metric='+41%', prima=34, dopo=96,
        problema_testo='Il sito di Arredamenti Colombo caricava in 4,1 secondi su mobile, con immagini non ottimizzate e una struttura costruita per una versione desktop del 2015. Il 68% dei visitatori da mobile abbandonava la pagina prima del caricamento completo, e solo l’1,2% arrivava al modulo contatti.',
        problema_stats=[('4,1 s', 'tempo di caricamento mobile'), ('68%', 'abbandono prima del caricamento'),
                         ('1,2%', 'tasso di conversione al modulo contatti')],
        soluzione_testo='Abbiamo ricostruito la base tecnica mantenendo intatti i contenuti e la struttura di navigazione a cui i clienti erano abituati, con redirect 301 per non perdere il posizionamento già acquisito.',
        soluzione_interventi=['Migrazione su base tecnica performante con generazione statica',
                               'Compressione e lazy loading di tutte le immagini del catalogo',
                               'Nuovo modulo contatti con notifica WhatsApp Business',
                               'SEO tecnica: dati strutturati per ogni prodotto'],
        risultati_testo='Sei settimane dopo la messa online, il punteggio PageSpeed mobile è passato da 34 a 96, con un tempo di caricamento sceso a 1,2 secondi.',
        risultati_stats=[('−2,9 s', 'di caricamento: da 4,1 a 1,2 secondi'), ('+41%', 'richieste di preventivo in sei mesi'),
                          ('Pag. 1', 'su Google per «arredamenti su misura Lissone»')],
        quote="Non ci aspettavamo che un problema “tecnico” portasse così tante richieste in più. Il sito adesso si apre prima che io finisca di sbloccare il telefono.",
        attribuzione='Marco Colombo, titolare',
    ),
    dict(
        slug='officine-riva', cliente='Officine Riva',
        titolo='Tre volte più veloce, stesso posizionamento su Google',
        settore='Meccanica industriale', citta='Monza (MB)', intervento='Restyling e migrazione',
        anno='2025', key_metric='3×', prima=27, dopo=93,
        problema_testo='Il sito precedente di Officine Riva era tecnicamente valido nei contenuti ma costruito su una piattaforma obsoleta, con un tempo di caricamento medio di 3,8 secondi e nessuna ottimizzazione per mobile.',
        problema_stats=[('3,8 s', 'tempo di caricamento mobile'), ('52%', 'traffico da mobile non ottimizzato'),
                         ('2,1%', 'tasso di conversione al modulo contatti')],
        soluzione_testo='Restyling tecnico completo mantenendo il posizionamento SEO esistente, con particolare attenzione ai redirect e alla struttura dati per i macchinari a catalogo.',
        soluzione_interventi=['Nuova base tecnica con generazione statica',
                               'Redirect 301 per tutte le pagine prodotto esistenti',
                               'Catalogo macchinari con schema.org Product',
                               'Compressione immagini tecniche ad alta risoluzione'],
        risultati_testo='Il punteggio PageSpeed è passato da 27 a 93 mantenendo invariato il posizionamento organico su tutte le parole chiave principali.',
        risultati_stats=[('3×', 'più veloce nel caricamento mobile'), ('0', 'posizioni perse in SEO durante la migrazione'),
                          ('+19%', 'richieste di preventivo in tre mesi')],
        quote='Temevamo di perdere il posizionamento che avevamo faticosamente conquistato. È rimasto identico, e la velocità del sito ora è irriconoscibile.',
        attribuzione='Laura Riva, responsabile marketing',
    ),
    dict(
        slug='studio-fontana', cliente='Studio Fontana',
        titolo="Un sito che si apre come un’app, senza costi da app store",
        settore='Studio professionale', citta='Milano', intervento='Sito progressivo PWA',
        anno='2024', key_metric='+63%', prima=31, dopo=96,
        problema_testo='I clienti di Studio Fontana tornavano spesso sul sito per consultare documenti e orari, ma ogni visita richiedeva un nuovo caricamento completo, con tempi di attesa fino a 5 secondi su connessioni mobili instabili.',
        problema_stats=[('5,0 s', 'tempo di caricamento su connessione debole'), ('0', 'funzionalità offline disponibili'),
                         ('41%', 'visite ripetute abbandonate')],
        soluzione_testo="Abbiamo trasformato il sito in una Progressive Web App installabile, con le pagine più consultate disponibili anche offline dopo la prima visita.",
        soluzione_interventi=['Service worker per il caricamento istantaneo dopo la prima visita',
                               'Installazione diretta da browser, senza store',
                               'Pagine chiave disponibili offline',
                               'Notifiche push opzionali per comunicazioni dello studio'],
        risultati_testo='Le visite ripetute si aprono ora in meno di un secondo, anche offline, con un aumento significativo delle richieste da parte di clienti già acquisiti.',
        risultati_stats=[('+63%', 'richieste ripetute da clienti esistenti'), ('<1 s', 'caricamento nelle visite successive'),
                          ('100%', 'pagine chiave disponibili offline')],
        quote="I nostri clienti installano il sito come un’app senza nemmeno accorgersene. Semplicemente, funziona sempre.",
        attribuzione='Elena Fontana, titolare dello studio',
    ),
    dict(
        slug='bb-il-cortile', cliente='B&B Il Cortile',
        titolo='Dalla terza pagina di Google alla prima, in otto settimane',
        settore='Ricettività turistica', citta='Como', intervento='SEO tecnica',
        anno='2025', key_metric='Pag. 1', prima=33, dopo=95,
        problema_testo='I contenuti del B&B Il Cortile erano curati, ma il sito non aveva dati strutturati, sitemap aggiornata né ottimizzazione Core Web Vitals: risultato, terza pagina su Google per le ricerche locali principali.',
        problema_stats=[('3ª pag.', 'posizionamento medio su Google'), ('0', 'dati strutturati presenti'),
                         ('2,4 s', 'tempo di caricamento mobile')],
        soluzione_testo='Intervento tecnico mirato su SEO e Core Web Vitals, senza toccare i contenuti già scritti, più ottimizzazione della scheda Google Business Profile.',
        soluzione_interventi=["Dati strutturati schema.org per l’attività ricettiva",
                               'Ottimizzazione Core Web Vitals fino a PageSpeed 95',
                               'Sitemap XML e struttura URL rivista',
                               'Ottimizzazione scheda Google Business Profile'],
        risultati_testo='In otto settimane il B&B è passato dalla terza alla prima pagina di Google per le ricerche locali principali, con un incremento diretto delle prenotazioni.',
        risultati_stats=[('Pag. 1', 'su Google per le ricerche locali principali'), ('+54%', 'prenotazioni dirette dal sito'),
                          ('95/100', 'PageSpeed mobile finale')],
        quote='Non abbiamo cambiato una parola del sito. Solo la parte tecnica, e le prenotazioni dirette sono aumentate più della metà.',
        attribuzione='Giulia Bianchi, gestione B&B Il Cortile',
    ),
]

TOOLS = [
    dict(slug='test-velocita', idx='/01', titolo='Test velocità',
         hero_titolo='Test di velocità del vostro sito',
         hero_sub='Misuriamo il PageSpeed reale del vostro sito su mobile e vi spieghiamo cosa significa, in italiano.',
         descrizione='Il PageSpeed reale del vostro sito, spiegato in italiano.', has_demo=True),
    dict(slug='check-gdpr', idx='/02', titolo='Check GDPR e cookie',
         hero_titolo='Il vostro sito è a norma GDPR?',
         hero_sub='Verifichiamo banner cookie, informative e consensi: cosa manca per essere a norma con il Garante Privacy.',
         descrizione='Banner, informative e consensi: cosa manca per essere a norma.', has_demo=False),
    dict(slug='analisi-seo', idx='/03', titolo='Analisi SEO on-page',
         hero_titolo='Analisi SEO della vostra pagina.',
         hero_sub='Controlliamo titoli, struttura e dati mancanti sulla pagina che conta di più per il vostro business.',
         descrizione='Titoli, struttura e dati mancanti sulla pagina che conta di più.', has_demo=False),
    dict(slug='roi-localizzazione', idx='/04', titolo='ROI localizzazione',
         hero_titolo='Quanto rende tradurre il vostro sito.',
         hero_sub='Stimiamo quanto può rendere tradurre il sito in inglese o tedesco per la vostra attività.',
         descrizione='Quanto rende tradurre il sito in inglese o tedesco.', has_demo=False),
]

CITY = dict(
    slug='milano', nome='Milano', eyebrow='MILANO E PROVINCIA', progetti=14, dal='2023',
    indirizzo='Via Andrea Solari 43, 20144 Milano (MI)', metro='M2 S. Agostino',
    orari='Lun–Ven 9:00–18:00', telefono='+39 02 1234 5678',
)

BLOG_POSTS = [
    dict(slug='perche-pagespeed-conta', data='05 MAG 2026',
         titolo='Perché il PageSpeed conta più del design',
         estratto='Un sito bellissimo che carica in 5 secondi perde più clienti di uno essenziale che carica in uno. I numeri dei nostri ultimi 12 progetti.',
         corpo='Un sito bellissimo che carica in 5 secondi perde più clienti di uno essenziale che carica in uno. Negli ultimi 12 progetti consegnati, il punteggio medio PageSpeed su mobile è stato 97, con un tempo di caricamento medio di 1,1 secondi. Questo articolo spiega come misuriamo la velocità e perché la mettiamo per iscritto nel contratto.'),
    dict(slug='redirect-301-senza-perdere-seo', data='18 APR 2026',
         titolo='Come migriamo un sito senza perdere il posizionamento SEO',
         estratto='Ogni migrazione tecnica comporta il rischio di perdere anni di posizionamento organico. Ecco il processo di redirect che usiamo per evitarlo.',
         corpo="Ogni migrazione tecnica comporta il rischio di perdere anni di posizionamento organico. In questo articolo spieghiamo il processo di audit, mappatura URL e redirect 301 che applichiamo prima di ogni restyling, con un caso reale in cui il posizionamento è rimasto invariato."),
    dict(slug='pwa-vs-app-nativa', data='02 APR 2026',
         titolo='PWA o app nativa? Cosa conviene a una PMI italiana',
         estratto='Sviluppare un’app nativa costa in media 15–30mila euro. Una Progressive Web App offre gran parte dei benefici a una frazione del costo.',
         corpo="Sviluppare un’app nativa costa in media 15–30mila euro e richiede manutenzione separata per iOS e Android. Una Progressive Web App offre installabilità, notifiche e funzionamento offline a una frazione del costo, senza revisione degli store. Ecco quando ha senso scegliere l’una o l’altra."),
    dict(slug='core-web-vitals-spiegati', data='20 MAR 2026',
         titolo='Core Web Vitals spiegati senza gergo tecnico',
         estratto='LCP, INP e CLS: cosa misurano davvero e perché Google li usa per decidere chi mostrare per primo nei risultati di ricerca.',
         corpo='LCP, INP e CLS sono le tre metriche che Google usa per valutare l’esperienza utente di un sito. In questo articolo le spieghiamo senza gergo tecnico, con esempi reali di cosa le peggiora e come si sistemano.'),
    dict(slug='gdpr-cookie-banner-regole', data='08 MAR 2026',
         titolo='Cookie banner GDPR: le regole che (quasi) nessuno rispetta',
         estratto='Il pulsante «Rifiuta» deve avere lo stesso peso visivo di «Accetta». Una regola semplice, ignorata dalla maggior parte dei siti italiani.',
         corpo='Il Garante Privacy richiede che il pulsante «Rifiuta» abbia lo stesso peso visivo del pulsante «Accetta» in un cookie banner. È una regola semplice, ma ignorata dalla maggior parte dei siti italiani che analizziamo. Ecco come costruiamo i nostri banner per essere a norma fin dal primo giorno.'),
    dict(slug='quanto-costa-davvero-un-sito', data='22 FEB 2026',
         titolo='Quanto costa davvero un sito web in Italia nel 2026',
         estratto='Dai 500 euro dei costruttori fai-da-te ai 20mila delle grandi agenzie: una mappa onesta dei prezzi e di cosa comprano davvero.',
         corpo="Dai 500 euro dei costruttori fai-da-te ai 20mila euro delle grandi agenzie, il mercato dei siti web in Italia è frammentato e poco trasparente. In questo articolo proviamo a mappare onestamente cosa si compra a ogni fascia di prezzo, incluso il nostro."),
]
