"""Контент студии — единый источник для генератора WP-страниц.

Сверено построчно с дизайн-хендоффом (design_handoff_studio_remarka/*.dc.html,
"Fidelity: High-fidelity... copy... final design intent"). Текст сервиса
"Siti aziendali" и футера — дословно из хендоффа. Для остальных пяти услуг
хендофф даёт только один полный пример (Siti aziendali) — их текст написан
по тому же паттерну (H1-обещание, «Per chi»/«Cosa include»/мини-кейс с
городом и подписью/«Confronta le tariffe»/трастовый вопрос в FAQ), но своими
словами, и привязан к четырём каноничным кейсам ниже вместо новых вымышленных
имён.
"""

SERVICES = [
    dict(
        # Единственная услуга, где в хендоффе дан полный авторский текст —
        # перенесено дословно (Servizio.dc.html).
        slug='siti-aziendali', title='Siti aziendali',
        breadcrumb='Servizio / Siti aziendali',
        hero_title='Il sito aziendale che carica in un secondo',
        hero_sub='Un sito web aziendale di quindici pagine, due lingue e un CMS per aggiornarlo da soli. Progettato per trasformare le visite in richieste di preventivo.',
        hero_stat_value='1,1 s', hero_stat_label='Caricamento medio (LCP) dei siti aziendali consegnati nel 2025.',
        per_chi_heading='Un sito web aziendale per chi vive di richieste, non di clic',
        per_chi=[
            'PMI manifatturiere con cataloghi tecnici e clienti B2B che confrontano fornitori.',
            'Studi professionali e società di servizi che vivono di reputazione e primo contatto.',
            "Aziende con clienti esteri: la versione inglese o tedesca è tradotta da madrelingua, inclusa.",
        ],
        include_heading='Tutto scritto nel preventivo',
        include=[
            'Fino a 15 pagine, struttura studiata sul funnel',
            'Due lingue incluse, tradotte da madrelingua',
            'CMS: testi e foto li aggiornate da soli',
            'SEO tecnica completa e dati strutturati',
            'GDPR: banner, informative e consensi a norma',
            'PageSpeed 90+ garantito da contratto',
            'Modulo contatti con notifiche immediate',
            '12 mesi di assistenza e misurazioni mensili',
        ],
        mini_caso=dict(
            cliente='TecnoIdraulica', citta='Bergamo', prima=29, dopo=94, link_slug='tecnoidraulica',
            testo='Sito aziendale in italiano e tedesco per un installatore con clienti in Alto Adige. Tre volte più richieste dal modulo contatti nel primo trimestre.',
            caption='GOOGLE PAGESPEED, MOBILE — RILEVAZIONI DOCUMENTATE',
        ),
        prezzo_range='€ 3.900–5.800',
        prezzo_lede='Prezzo chiuso nel preventivo, consegna in 3 settimane. Fattura elettronica, pagamento in tre tranche.',
        prezzo_note=[
            'Numero di pagine e schede prodotto oltre le 15 incluse.',
            'Lingue aggiuntive oltre le due comprese.',
            'Integrazioni con gestionale, CRM o listini esterni.',
        ],
        faq_heading='Tre domande tipiche',
        faq=[
            ('Possiamo tenere i testi attuali?', 'Sì. Li revisioniamo gratuitamente in fase di analisi e vi diciamo cosa conviene riscrivere, e perché.'),
            ('Il dominio resta nostro?', 'Sempre. Dominio, hosting e codice sono intestati a voi dal primo giorno. Nessun vincolo con lo studio.'),
            ('E dopo i 12 mesi di assistenza?', "Canone annuale facoltativo, con lo stesso perimetro. Oppure il sito resta a voi così com’è: è vostro."),
        ],
    ),
    dict(
        slug='e-commerce', title='E-commerce',
        breadcrumb='Servizio / E-commerce',
        hero_title='Il negozio online che non perde clienti nel checkout',
        hero_sub='Realizzazione siti e-commerce con catalogo veloce, checkout in un passaggio e fatturazione elettronica integrata: pensata per chi vende, non solo per chi naviga.',
        hero_stat_value='1,4 s', hero_stat_label='Caricamento medio (LCP) degli e-commerce consegnati nel 2025.',
        per_chi_heading='Realizzazione siti e-commerce per chi vende sul serio, non solo espone',
        per_chi=[
            'Attività che vendono online ma perdono clienti proprio nel checkout.',
            'Negozi fisici pronti ad aprire un canale e-commerce senza improvvisare.',
            'Chi ha bisogno di fatturazione elettronica automatica, non di un plugin da rincorrere.',
        ],
        include_heading='Tutto scritto nel preventivo',
        include=[
            'Catalogo prodotti illimitato con varianti',
            'Checkout in un solo passaggio',
            'Pagamenti con carta, PayPal e bonifico',
            'Fatturazione elettronica via SDI integrata',
            'Gestione magazzino e spedizioni',
            'SEO tecnica per le pagine prodotto',
            'PageSpeed 90+ garantito da contratto',
            '12 mesi di assistenza e misurazioni mensili',
        ],
        mini_caso=dict(
            cliente='Cantina Serralta', citta='Asti', prima=41, dopo=97, link_slug='cantina-serralta',
            testo='Catalogo vini tradotto in tre lingue con checkout in un solo passaggio: le vendite dirette dal sito sono cresciute del 63% in un anno.',
            caption='GOOGLE PAGESPEED, MOBILE — RILEVAZIONI DOCUMENTATE',
        ),
        prezzo_range='€ 7.500–14.000',
        prezzo_lede='Prezzo chiuso nel preventivo, consegna in 6 settimane. Fattura elettronica, pagamento in tre tranche.',
        prezzo_note=[
            'Numero di prodotti e varianti oltre il catalogo base.',
            'Integrazioni con corrieri e magazzino esterno.',
            'Metodi di pagamento aggiuntivi oltre carta, PayPal e bonifico.',
        ],
        faq_heading='Tre domande tipiche',
        faq=[
            ('Gestite anche la fatturazione elettronica?', 'Sì, ogni ordine genera automaticamente una fattura elettronica conforme SDI.'),
            ("Posso vendere anche all’estero?", 'Sì, il catalogo supporta più lingue e più valute su richiesta.'),
            ('Il dominio e i dati dei clienti restano nostri?', 'Sempre. Dominio, database ordini e codice sono intestati a voi dal primo giorno.'),
        ],
    ),
    dict(
        slug='siti-pwa', title='Siti progressivi PWA',
        breadcrumb='Servizio / Siti progressivi PWA',
        hero_title="Un sito che si apre come un’app, senza passare dagli store",
        hero_sub="Una progressive web app installabile, che funziona offline e si apre all’istante anche alla decima visita: senza i costi e i tempi di App Store e Play Store.",
        hero_stat_value='0,9 s', hero_stat_label='Caricamento medio (LCP) delle PWA consegnate nel 2025.',
        per_chi_heading='Una progressive web app per chi ha clienti che tornano, non solo che passano',
        per_chi=[
            'Attività con clienti che tornano spesso a consultare il sito.',
            "Chi vuole un’app senza i costi e le revisioni di App Store e Play Store.",
            'Servizi che devono funzionare bene anche con connessione debole, in cantiere o in showroom.',
        ],
        include_heading='Tutto scritto nel preventivo',
        include=[
            'Installabile su smartphone come un’app',
            'Funziona offline per le pagine già visitate',
            'Notifiche push opzionali',
            'Caricamento istantaneo dopo la prima visita',
            'Service worker configurato e testato',
            'SEO tecnica completa e dati strutturati',
            'PageSpeed 90+ garantito da contratto',
            '12 mesi di assistenza e misurazioni mensili',
        ],
        mini_caso=dict(
            cliente='Arredamenti Colombo', citta='Lissone (MB)', prima=34, dopo=96, link_slug='arredamenti-colombo',
            testo="Il catalogo si apre all’istante e resta consultabile anche offline in showroom: +41% di richieste di preventivo in sei mesi.",
            caption='GOOGLE PAGESPEED, MOBILE — MEDIA DI 3 RILEVAZIONI',
        ),
        prezzo_range='€ 4.900–7.200',
        prezzo_lede='Prezzo chiuso nel preventivo, consegna in 4 settimane. Fattura elettronica, pagamento in tre tranche.',
        prezzo_note=[
            'Funzionalità offline richieste oltre le pagine base.',
            'Notifiche push e integrazioni native aggiuntive.',
            'Numero di pagine e sezioni oltre quelle incluse.',
        ],
        faq_heading='Tre domande tipiche',
        faq=[
            ('Serve pubblicarlo sugli store?', 'No, si installa direttamente dal browser: nessuna revisione Apple o Google necessaria.'),
            ('Funziona su tutti gli smartphone?', 'Sì, è compatibile con iOS e Android tramite qualsiasi browser moderno.'),
            ('Posso passare da un sito esistente a una PWA?', 'Sì, è un percorso di restyling tecnico che manteniamo trasparente per i motori di ricerca.'),
        ],
    ),
    dict(
        slug='restyling-migrazione', title='Restyling e migrazione',
        breadcrumb='Servizio / Restyling e migrazione',
        hero_title='Il vostro sito, ricostruito: stessi contenuti, il triplo della velocità',
        hero_sub='Rifacimento sito web senza perdere posizionamento e senza riscrivere i contenuti: cambia solo la base tecnica, e cambia in meglio.',
        hero_stat_value='1,2 s', hero_stat_label='Caricamento medio (LCP) dei restyling consegnati nel 2025.',
        per_chi_heading='Rifacimento sito web per chi ha già i contenuti giusti, e la tecnologia sbagliata',
        per_chi=[
            'Chi ha un sito lento ma non vuole perdere posizionamento SEO faticosamente conquistato.',
            'Attività con contenuti validi ma una tecnologia costruita più di cinque anni fa.',
            'Chi ha ricevuto un preventivo di rifacimento completo troppo costoso per quello che serve davvero.',
        ],
        include_heading='Tutto scritto nel preventivo',
        include=[
            'Audit tecnico del sito attuale',
            'Migrazione dei contenuti esistenti',
            'Redirect 301 per mantenere il posizionamento SEO',
            'Nuova base tecnica performante',
            'Ottimizzazione immagini e font',
            'Test comparativo prima/dopo su PageSpeed',
            'PageSpeed 90+ garantito da contratto',
            '12 mesi di assistenza e misurazioni mensili',
        ],
        mini_caso=dict(
            cliente='Arredamenti Colombo', citta='Lissone (MB)', prima=34, dopo=96, link_slug='arredamenti-colombo',
            testo='Stessi contenuti, stessa struttura di navigazione a cui i clienti erano abituati: solo la base tecnica è cambiata, con redirect 301 su ogni URL esistente.',
            caption='GOOGLE PAGESPEED, MOBILE — MEDIA DI 3 RILEVAZIONI',
        ),
        prezzo_range='€ 2.900–4.800',
        prezzo_lede='Prezzo chiuso nel preventivo, consegna in 3 settimane. Fattura elettronica, pagamento in tre tranche.',
        prezzo_note=[
            'Numero di pagine da migrare oltre le prime 20.',
            'Complessità delle integrazioni esistenti da mantenere.',
            'Necessità di redesign grafico oltre alla base tecnica.',
        ],
        faq_heading='Tre domande tipiche',
        faq=[
            ('Perdo il posizionamento su Google?', 'No, impostiamo redirect 301 corretti per ogni URL esistente prima di andare online.'),
            ('Devo riscrivere i contenuti?', 'No, il restyling tecnico mantiene i contenuti esistenti; li aggiorniamo solo su richiesta.'),
            ('Quanto dura la migrazione?', 'In media 3 settimane, con un ambiente di prova visibile fin dalla prima settimana.'),
        ],
    ),
    dict(
        slug='seo-tecnica', title='SEO tecnica',
        breadcrumb='Servizio / SEO tecnica',
        hero_title='Struttura e dati a posto, prima ancora di scrivere i contenuti',
        hero_sub='Core Web Vitals, dati strutturati e sitemap corretti: è la SEO tecnica, quella che il copywriting da solo non risolve.',
        hero_stat_value='90+', hero_stat_label='Punteggio Core Web Vitals garantito da contratto.',
        per_chi_heading='La SEO tecnica per chi ha buoni contenuti e scarsa visibilità',
        per_chi=[
            'Siti con buoni contenuti ma scarsa visibilità su Google.',
            'Chi ha già investito in copywriting senza vedere risultati in classifica.',
            'Attività che competono in mercati locali affollati, dove ogni posizione conta.',
        ],
        include_heading='Tutto scritto nel preventivo',
        include=[
            'Audit tecnico SEO completo',
            'Dati strutturati (schema.org) per ogni tipo di pagina',
            'Ottimizzazione Core Web Vitals',
            'Sitemap XML e file robots ottimizzati',
            'Struttura URL e gerarchia dei contenuti',
            'Ottimizzazione meta title e description',
            'Report mensile di posizionamento',
            'PageSpeed 90+ garantito da contratto',
        ],
        mini_caso=dict(
            cliente='Studio Legale Fontana', citta='Milano', prima=38, dopo=95, link_slug='studio-legale-fontana',
            testo='Sito vetrina con blog di settore sistemato lato tecnico: da pagina 3 a pagina 1 su Google per dodici parole chiave di settore in otto settimane.',
            caption='GOOGLE PAGESPEED, MOBILE — RILEVAZIONI DOCUMENTATE',
        ),
        prezzo_range='€ 1.800–3.500',
        prezzo_lede='Prezzo chiuso nel preventivo, consegna in 3 settimane. Fattura elettronica, pagamento in tre tranche.',
        prezzo_note=[
            'Numero di pagine da ottimizzare oltre le prime 20.',
            'Presenza di contenuti multilingua da trattare.',
            'Storico tecnico da correggere prima di intervenire.',
        ],
        faq_heading='Tre domande tipiche',
        faq=[
            ('In quanto tempo si vedono risultati?', 'I miglioramenti tecnici sono immediati; il posizionamento su Google richiede in media 6–10 settimane.'),
            ('Scrivete anche i contenuti?', 'Il servizio è tecnico; per la scrittura dei testi lavoriamo con copywriter partner su richiesta.'),
            ('Fate SEO locale?', 'Sì, includiamo l’ottimizzazione della scheda Google Business Profile quando pertinente.'),
        ],
    ),
    dict(
        slug='siti-multilingue', title='Siti multilingue',
        breadcrumb='Servizio / Siti multilingue',
        hero_title='Quattro lingue tradotte da madrelingua, non da un plugin',
        hero_sub="Un sito web multilingua è il mestiere del gruppo Remarka dal 2001: traduzione professionale, non automatica, con SEO multilingue corretta fin dal primo giorno.",
        hero_stat_value='4', hero_stat_label='Lingue native disponibili: italiano, inglese, tedesco, francese.',
        per_chi_heading='Un sito web multilingua per chi vende oltre confine, non solo in italiano',
        per_chi=[
            'Aziende che esportano o accolgono clienti stranieri.',
            'Attività turistiche con visitatori internazionali.',
            'Chi ha usato finora traduzioni automatiche poco professionali, e i clienti se ne sono accorti.',
        ],
        include_heading='Tutto scritto nel preventivo',
        include=[
            'Traduzione professionale da madrelingua (non plugin)',
            'Fino a 4 lingue: italiano, inglese, tedesco, francese',
            'Selettore lingua persistente',
            'SEO multilingue con hreflang corretti',
            'Contenuti localizzati, non solo tradotti',
            'Revisione linguistica da parte del gruppo Remarka',
            'PageSpeed 90+ garantito da contratto',
            '12 mesi di assistenza e misurazioni mensili',
        ],
        mini_caso=dict(
            cliente='Cantina Serralta', citta='Asti', prima=41, dopo=97, link_slug='cantina-serralta',
            testo='Con il catalogo tradotto in tre lingue da madrelingua del gruppo Remarka, le vendite dirette dal sito sono cresciute del 63% in un anno.',
            caption='GOOGLE PAGESPEED, MOBILE — RILEVAZIONI DOCUMENTATE',
        ),
        prezzo_range='€ 3.200–5.500',
        prezzo_lede='Prezzo chiuso nel preventivo, consegna in 4 settimane. Fattura elettronica, pagamento in tre tranche.',
        prezzo_note=[
            'Numero di lingue aggiuntive oltre le due comprese.',
            'Volume di contenuti da tradurre oltre le pagine base.',
            'Necessità di revisione periodica dopo la consegna.',
        ],
        faq_heading='Tre domande tipiche',
        faq=[
            ('Le traduzioni sono automatiche?', 'No, sono realizzate da traduttori madrelingua del gruppo Remarka, non da plugin automatici.'),
            ('Posso aggiungere una lingua in futuro?', 'Sì, la struttura multilingue è predisposta per aggiungere nuove lingue senza rifare il sito.'),
            ('La SEO funziona in tutte le lingue?', 'Sì, ogni lingua ha URL e tag hreflang dedicati per essere indicizzata correttamente da Google.'),
        ],
    ),
]

# Quattro casi studio completi — stesso set di nomi usato in tutto il sito
# (trust strip, mini-casi dei servizi, Milano). Solo "Arredamenti Colombo" ha
# un testo completo dato dal hendoff (Caso Arredamenti Colombo.dc.html),
# copiato qui parola per parola; gli altri tre sono scritti nello stesso
# registro, ancorati ai fatti confermati nel hendoff (settore/città/intervento/
# punteggi/testimonial) dove disponibili (Servizio.dc.html per TecnoIdraulica,
# Milano.dc.html per Studio Legale Fontana, Casi Studio.dc.html per tutti).
CASES = [
    dict(
        slug='arredamenti-colombo', cliente='Arredamenti Colombo',
        sito='arredamenticolombo.it',
        titolo='Da 34 a 96 in sei settimane, senza fermare lo showroom',
        settore='Arredo su misura', citta='Lissone (MB)', intervento='Restyling + PWA + SEO',
        anno='2025', key_metric='+41%', prima=34, dopo=96,
        caption='GOOGLE PAGESPEED, MOBILE — MEDIA DI 3 RILEVAZIONI',
        problema_testo='Il sito del 2019 caricava gallerie fotografiche complete su ogni pagina: 4,1 secondi di attesa media su mobile, dove arrivava il 78% delle visite. Le richieste di preventivo passavano quasi solo dal telefono, e le campagne locali portavano visite che se ne andavano prima di vedere il primo divano.',
        problema_stats=[('4,1 s', 'di caricamento medio su mobile'), ('68%', 'di rimbalzo dalle campagne locali'),
                         ('1,2%', 'di visite che diventavano richieste')],
        soluzione_testo='Sei settimane, showroom sempre online: il sito nuovo è cresciuto su un ambiente di prova ed è andato in produzione in una notte, con i redirect già pronti.',
        soluzione_interventi=[
            "Architettura PWA: il catalogo si apre all’istante e resta consultabile anche offline, in showroom.",
            'Fotografie ricompresse in AVIF con caricamento progressivo: −82% di peso a parità di qualità visibile.',
            'Una pagina per ogni lavorazione, con dati strutturati: «arredamenti su misura Lissone» da pagina 3 a pagina 1.',
            'Richiesta di preventivo in due passaggi, con notifica immediata in showroom via WhatsApp Business.',
        ],
        risultati_testo='Sei settimane dopo la messa online, il punteggio PageSpeed mobile è passato da 34 a 96, con un tempo di caricamento sceso a 1,2 secondi.',
        risultati_stats=[('1,2 s', 'caricamento su mobile (da 4,1 s)'), ('+41%', 'richieste di preventivo in sei mesi'),
                          ('Pag. 1', 'per «arredamenti su misura Lissone»')],
        quote='Prima il sito era un biglietto da visita lento. Adesso è il commerciale più veloce che abbiamo.',
        attribuzione='Paolo Colombo — titolare, Arredamenti Colombo S.r.l.',
    ),
    dict(
        slug='cantina-serralta', cliente='Cantina Serralta',
        sito='cantinaserralta.it',
        titolo='Da 41 a 97, con le vendite dirette cresciute del 63% in un anno',
        settore='Vino', citta='Asti', intervento='E-commerce in 3 lingue',
        anno='2025', key_metric='+63%', prima=41, dopo=97,
        caption='GOOGLE PAGESPEED, MOBILE — RILEVAZIONI DOCUMENTATE',
        problema_testo="Il vecchio store impiegava oltre 6 secondi a caricare le pagine prodotto, con un checkout in quattro passaggi e nessuna versione in lingua per i clienti esteri che scrivevano via email prima di ogni ordine. Il tasso di abbandono carrello sfiorava il 70%.",
        problema_stats=[('6,1 s', 'caricamento medio pagina prodotto'), ('4', 'passaggi per completare un ordine'),
                         ('0', 'lingue oltre l’italiano')],
        soluzione_testo="Catalogo ricostruito su base tecnica performante, checkout ridotto a un solo passaggio, traduzione professionale in inglese e tedesco da madrelingua del gruppo Remarka.",
        soluzione_interventi=[
            'Catalogo vini con varianti (formato, annata) e caricamento immagini differito',
            'Checkout in un solo passaggio, con pagamento carta, PayPal e bonifico',
            'Fatturazione elettronica via SDI generata automaticamente su ogni ordine',
            'Traduzione professionale in inglese e tedesco, non plugin automatico',
        ],
        risultati_testo="In un anno, con il sito tradotto e il checkout semplificato, le vendite dirette dal sito sono cresciute del 63%, senza intermediari.",
        risultati_stats=[('41 → 97', 'punteggio PageSpeed mobile'), ('+63%', 'vendite dirette dal sito in un anno'),
                          ('3', 'lingue disponibili, tradotte da madrelingua')],
        quote='Il sito vecchio ci faceva perdere ordini esteri già in carrello. Ora chi scrive in tedesco trova tutto in tedesco, e ordina.',
        attribuzione='Titolare, Cantina Serralta',
    ),
    dict(
        slug='tecnoidraulica', cliente='TecnoIdraulica',
        sito='tecnoidraulica.it',
        titolo='Tre volte più richieste dal modulo contatti in un trimestre',
        settore='Impianti idraulici', citta='Bergamo', intervento='Sito aziendale IT/DE',
        anno='2025', key_metric='3×', prima=29, dopo=94,
        caption='GOOGLE PAGESPEED, MOBILE — RILEVAZIONI DOCUMENTATE',
        problema_testo="Il sito precedente di TecnoIdraulica era una singola pagina statica in italiano, senza modulo contatti tracciabile e senza alcuna versione per i clienti di lingua tedesca dell’Alto Adige, che rappresentavano già un quarto del fatturato.",
        problema_stats=[('1', 'pagina totale, nessuna scheda per intervento'), ('0', 'lingue oltre l’italiano'),
                         ('5,4 s', 'caricamento medio su mobile')],
        soluzione_testo="Sito aziendale con schede per ogni tipo di intervento, tradotto in tedesco da madrelingua del gruppo Remarka, con modulo contatti che notifica in tempo reale via WhatsApp Business.",
        soluzione_interventi=[
            'Struttura a schede per ogni tipo di impianto e intervento',
            'Versione in tedesco tradotta da madrelingua, non automatica',
            'Modulo contatti con notifica immediata via WhatsApp Business',
            'SEO tecnica locale per le ricerche in Alto Adige',
        ],
        risultati_testo="Nel primo trimestre dalla pubblicazione, le richieste dal modulo contatti sono triplicate, in buona parte dalla versione in tedesco.",
        risultati_stats=[('29 → 94', 'punteggio PageSpeed mobile'), ('3×', 'richieste dal modulo contatti nel trimestre'),
                          ('2', 'lingue: italiano e tedesco')],
        quote='I clienti di Bressanone e Merano finalmente trovano tutto in tedesco. Le richieste sono triplicate senza cambiare una vite del nostro lavoro.',
        attribuzione='Titolare, TecnoIdraulica',
    ),
    dict(
        slug='studio-legale-fontana', cliente='Studio Legale Fontana',
        sito='studiolegalefontana.it',
        titolo='Da pagina 3 a pagina 1 su Google, in otto settimane',
        settore='Studio legale', citta='Milano', intervento='Sito vetrina + blog',
        anno='2025', key_metric='Pag. 1', prima=38, dopo=95,
        caption='GOOGLE PAGESPEED, MOBILE — RILEVAZIONI DOCUMENTATE',
        problema_testo="I contenuti del blog di settore di Studio Legale Fontana erano curati, ma il sito non aveva dati strutturati né sitemap aggiornata: risultato, terza pagina su Google per le dodici parole chiave che portavano più richieste.",
        problema_stats=[('3ª pag.', 'posizionamento medio su Google'), ('0', 'dati strutturati presenti'),
                         ('2,6 s', 'tempo di caricamento mobile')],
        soluzione_testo="Intervento tecnico mirato su SEO e Core Web Vitals, senza toccare una parola dei contenuti già scritti, più ottimizzazione della scheda Google Business Profile.",
        soluzione_interventi=[
            'Dati strutturati schema.org per lo studio e ogni articolo del blog',
            'Ottimizzazione Core Web Vitals fino a PageSpeed 95',
            'Sitemap XML e struttura URL rivista',
            'Ottimizzazione della scheda Google Business Profile',
        ],
        risultati_testo="In otto settimane lo studio è passato dalla terza alla prima pagina di Google per dodici parole chiave di settore, senza riscrivere un solo articolo.",
        risultati_stats=[('38 → 95', 'punteggio PageSpeed mobile'), ('Pag. 1', 'su Google per 12 parole chiave di settore'),
                          ('12', 'parole chiave portate in prima pagina')],
        quote='Non abbiamo cambiato una parola del blog. Solo la parte tecnica, e in due mesi eravamo in prima pagina.',
        attribuzione='Titolare, Studio Legale Fontana',
    ),
]

# Sette strumenti gratuiti di /strumenti/ (Remarka Lab). Campo `tipo` = modulo
# JS del widget (speed|seo|a11y|co2|gdpr|ai|roi|checkup), letto dal generatore
# per rendere la markup corretta secondo il contratto data-* di remarka.js.
# `come_funziona`: 3 passi (titolo, testo). `faq`: 3 (domanda, risposta).
# `cta`: blocco finale scuro che rimanda al servizio a pagamento pertinente.
# Tono: numeri, «voi», disclaimer onesti (GDPR indicativo/non legale; ROI stima).
#
# 'check-up-completo' (tipo 'checkup', M2 — docs/piano-checkup-sito.md) è
# l'ottavo strumento, featured: orchestra le altre sette misure in un unico
# punteggio «Salute del sito». Testi presi alla lettera da
# docs/copy-checkup.md §2.2/§2.3 (fonte unica per M2/M3). Non ha 'migliorare'
# (build_tool tratta la chiave come opzionale per questo tipo).
TOOLS = [
    dict(slug='check-up-completo', idx='/00', tipo='checkup', titolo='Check-up completo',
         hero_titolo='Il check-up completo del vostro sito web',
         hero_sub='Sette strumenti gratuiti in una sola analisi. Incollate l’indirizzo: in meno di un minuto vedete un punteggio di salute da 0 a 100, i sette semafori che lo compongono e i tre interventi più urgenti. La misura è quella vera di Google PageSpeed Insights, affiancata dalle nostre verifiche su privacy e prontezza AI. Il report completo, pagina per pagina, ve lo inviamo in PDF.',
         descrizione='Sette strumenti gratuiti in una sola analisi.', has_demo=True,
         come_funziona=[
             ('Incollate l’indirizzo', 'La home o la pagina che porta più visite. Nessuna registrazione, nessun dato di pagamento.'),
             ('Analizziamo su sette fronti', 'Un’unica interrogazione all’API Google PageSpeed (prestazioni, SEO, accessibilità, best practice) più le nostre verifiche su privacy/cookie e prontezza AI, letti dal nostro server come farebbe un visitatore.'),
             ('Leggete il punteggio e le priorità', 'Salute 0–100, i sette semafori spiegati in italiano e i tre interventi che pesano di più. Il report completo arriva in PDF.'),
         ],
         faq=[
             ('Il punteggio è quello vero di Google?', 'Per prestazioni, SEO, accessibilità e best practice sì: arrivano dall’API ufficiale PageSpeed Insights, strategia mobile. Privacy, prontezza AI e CO₂ sono nostre verifiche, con il metodo dichiarato in ogni sezione.'),
             ('Il check-up GDPR sostituisce un consulente privacy?', 'No. È una verifica tecnica indicativa a quattro segnali: intercetta i problemi evidenti — banner assente, tracker prima del consenso — ma non è un parere legale e non sostituisce un consulente.'),
             ('Cosa ricevo nel report PDF che non vedo già a schermo?', 'A schermo vedete il punteggio, i sette semafori e le tre priorità. Nel PDF trovate una pagina per dimensione con tutte le criticità rilevate, le raccomandazioni operative in ordine di impatto e cosa faremmo noi, con i nostri riferimenti aziendali.'),
         ],
         metodologia=('Che cosa misura davvero il check-up completo', [
             'Dietro il punteggio non c’è una scatola nera. Quattro delle sette dimensioni — prestazioni, SEO, accessibilità e best practice — arrivano dall’API PageSpeed Insights di Google, la stessa che alimenta pagespeed.web.dev: interroghiamo Lighthouse in strategia mobile, perché è la versione del sito che Google usa per posizionarvi. Le altre tre le calcoliamo noi: la conformità privacy la leggiamo dall’HTML della pagina (banner, informative, tracker prima del consenso), la prontezza AI da quattro segnali tecnici — llms.txt, accesso ai crawler, dati strutturati, sitemap — e l’impronta di CO₂ dal peso reale della pagina, con il modello Sustainable Web Design.',
             'Ogni dimensione entra nel voto con un peso dichiarato: le prestazioni valgono di più (25 su 100), la CO₂ di meno (5). È giusto sapere anche cosa il check-up non fa: non è un parere legale sulla privacy — è una verifica indicativa a quattro segnali — e non promette una posizione su Google. È la fotografia tecnica precisa del vostro sito, non una promessa di vendita.',
         ]),
         lettura=('Come si legge lo stato di salute del sito', [
             'Il punteggio di salute è la media pesata dei sette semafori, non un voto a sensazione. Si legge come un semaforo: da 90 in su siete in fascia verde (eccellente), da 75 a 89 è buono, tra 50 e 74 c’è margine concreto, sotto 50 è critico e diventa la priorità. Ogni dimensione porta lo stesso codice colore, così capite in un colpo d’occhio dove il sito è solido e dove perde punti.',
             'Due letture da evitare. Un voto alto non significa «primi su Google»: significa che le fondamenta tecniche sono sane. E se una misura risulta «N/D» non è un guasto del vostro sito: a volte Google è saturo, a volte il sito rifiuta la lettura automatica. In quel caso calcoliamo la salute sulle misure riuscite e ve lo diciamo con chiarezza.',
         ]),
         cta=dict(heading='Vogliamo sistemare noi le priorità?',
                  testo='Dal punteggio al preventivo: analizziamo il report insieme e vi diamo un piano d’intervento a prezzo chiuso, con PageSpeed 90+ garantito da contratto.',
                  buttons=[('Richiedi la consulenza — gratis', '/#contatti', None),
                           ('Vedi tutti gli strumenti', '/strumenti/', 'outline')])),
    dict(slug='test-velocita', idx='/01', tipo='speed', titolo='Test velocità',
         hero_titolo='Test velocità sito web: il punteggio reale di Google',
         hero_sub='Punteggio Google PageSpeed e le tre metriche che lo determinano — LCP, INP, CLS — spiegate in italiano. Strategia mobile, dati reali dall’API di Google. Senza registrazione.',
         descrizione='Il PageSpeed reale del vostro sito, spiegato in italiano.', has_demo=True,
         come_funziona=[
             ('Incollate l’indirizzo', 'Scrivete l’URL del sito: la home o la pagina interna che porta più visite.'),
             ('Misuriamo con Google', 'Interroghiamo l’API PageSpeed Insights in strategia mobile — gli stessi dati che Google usa per il posizionamento.'),
             ('Leggete cosa frena il sito', 'Punteggio 0–100 e le tre metriche Core Web Vitals spiegate in italiano, senza gergo tecnico.'),
         ],
         faq=[
             ('Il punteggio è quello vero di Google?', 'Sì: arriva dall’API ufficiale PageSpeed Insights, strategia mobile. È lo stesso motore che trovate su pagespeed.web.dev.'),
             ('Perché misurate solo il mobile?', 'Perché Google indicizza e classifica in base alla versione mobile del sito. Il punteggio desktop, più alto quasi ovunque, conta poco per il posizionamento.'),
             ('Un punteggio basso danneggia le vendite?', 'Sotto i 50, gran parte dei visitatori da mobile abbandona prima del caricamento completo: le campagne portano clic che non diventano richieste.'),
         ],
         metodologia=('Cosa misura davvero questo test dei tempi di caricamento', [
             'Dietro il punteggio c’è un motore solo: l’API PageSpeed Insights di Google, la stessa che alimenta pagespeed.web.dev. Interroghiamo Lighthouse in strategia mobile, perché è la versione del sito che Google usa per posizionarvi. Il numero da 0 a 100 nasce in laboratorio, con un telefono e una connessione simulati e standardizzati: così due misurazioni della stessa pagina restano confrontabili nel tempo. Dove il vostro sito riceve abbastanza traffico reale, aggiungiamo anche i Core Web Vitals raccolti sul campo dagli utenti veri di Chrome.',
             'È giusto sapere cosa questo test non guarda. Non giudica la qualità dei testi, non conta i link in entrata, non misura la sicurezza del server né quanto vendete: pesa solo l’esperienza di caricamento di una singola pagina. Un punteggio alto non è la promessa di un primo posto su Google, ma una base tecnica sana su cui tutto il resto lavora meglio. Preferiamo dirlo chiaro: è la fotografia precisa di un aspetto, non la diagnosi completa del sito.',
         ]),
         lettura=('Come leggere il punteggio delle prestazioni del sito', [
             'Il risultato si legge come un semaforo. Da 90 a 100 siete in fascia verde: la pagina compare in fretta anche in mobilità, sul 4G di città come ai bordi della copertura. Tra 50 e 89 la velocità è nella media del web italiano, con margini concreti di guadagno. Sotto 50 siete nel rosso: buona parte dei visitatori da smartphone se ne va prima che appaia la prima riga, e ogni euro investito in pubblicità rende molto meno.',
             'Due falsi allarmi ricorrenti. Il valore oscilla di qualche punto tra una prova e l’altra: è normale, dipende dai server di misura di Google, non dal vostro sito — contano i grandi salti, non i due punti di scarto. E non spaventatevi se il desktop segna 95 e il mobile 40: quasi tutti i siti hanno questo divario, ma è il mobile a decidere la classifica. Guardate sempre quel numero.',
         ]),
         migliorare=dict(h2='Come velocizzare il sito web: cinque interventi concreti',
             intro='Un punteggio basso nasce quasi sempre dalle stesse cause, e le prime sono anche le più economiche da correggere.',
             punti=[
                 ('Alleggerite le immagini', 'Convertite le fotografie in WebP o AVIF e attivate il caricamento differito: è la causa numero uno della lentezza e spesso, da sola, dimezza i tempi di attesa.'),
                 ('Attivate la cache', 'Una cache di pagina e del browser evita al server di ricostruire tutto a ogni visita: mezza giornata di lavoro, risultato misurabile da subito.'),
                 ('Sfoltite CSS e JavaScript', 'Portate in linea il CSS critico, rimandate il resto e togliete gli script di terze parti che non servono: meno codice da eseguire, prima visualizzazione più rapida.'),
                 ('Scegliete un hosting all’altezza', 'Un server condiviso e sovraffollato risponde in un secondo prima ancora di iniziare: un hosting adeguato, con una CDN davanti, taglia quell’attesa iniziale.'),
                 ('Controllate i font', 'Limitate le famiglie di caratteri, precaricate quelle essenziali e usate font-display swap, così il testo appare subito invece di restare invisibile.'),
             ],
             links=[
                 ('Vogliamo intervenire noi: scopri il restyling tecnico', '/servizi/restyling-migrazione/'),
                 ('Approfondisci: le 7 cause reali di un sito lento', '/blog/sito-lento-cause-costi/'),
             ]),
         cta=dict(heading='Vogliamo sistemare noi questi problemi?',
                  testo='Report gratuito con le cause, le priorità e un preventivo chiuso: PageSpeed 90+ garantito da contratto.',
                  buttons=[('Richiedi l’analisi completa', '/#contatti', None),
                           ('Scopri la SEO tecnica', '/servizi/seo-tecnica/', 'outline')])),
    dict(slug='analisi-seo', idx='/02', tipo='seo', titolo='Analisi SEO on-page',
         hero_titolo='Analisi SEO on-page: cosa vede Google sulla vostra pagina',
         hero_sub='Titolo, struttura dei contenuti e dati mancanti sulla pagina che conta di più per il vostro business. Punteggio SEO di Google e le correzioni concrete, in italiano. Senza registrazione.',
         descrizione='Titoli, struttura e dati mancanti sulla pagina che conta di più.', has_demo=False,
         come_funziona=[
             ('Scegliete la pagina giusta', 'Non per forza la home: la pagina che deve posizionarsi — un servizio, una scheda, un articolo.'),
             ('Google la analizza', 'Usiamo la categoria SEO di Lighthouse via API PageSpeed: titoli, meta description, tag, link e struttura.'),
             ('Vedete cosa correggere', 'Punteggio 0–100 e la lista degli elementi on-page da sistemare, in ordine di priorità.'),
         ],
         faq=[
             ('Questa analisi fa posizionare il sito?', 'Da sola no: verifica le basi tecniche on-page (titoli, struttura, dati). Il posizionamento dipende anche da contenuti e autorevolezza, che richiedono tempo.'),
             ('Che differenza c’è con l’analisi dei contenuti?', 'Qui controlliamo la parte tecnica della pagina, quella che Google legge. La qualità dei testi è un lavoro separato, che facciamo con copywriter partner.'),
             ('Analizza tutto il sito?', 'No: una pagina alla volta, quella che indicate. È l’unità su cui Google valuta la pertinenza per una ricerca.'),
         ],
         metodologia=('Che cosa controlla davvero l’audit SEO della pagina', [
             'Anche qui il motore è Google: usiamo la categoria SEO di Lighthouse attraverso l’API PageSpeed, in strategia mobile. In pochi secondi Lighthouse legge la pagina come farebbe il crawler e verifica gli elementi tecnici on-page: presenza e unicità del title, meta description, tag corretti, testi dei link descrittivi, indicizzabilità, leggibilità sullo schermo del telefono. Ne esce un punteggio da 0 a 100 con l’elenco puntuale di ciò che non supera il controllo.',
             'Vale la pena chiarire i confini. Questo esame guarda la struttura tecnica di una singola pagina, non la qualità dei contenuti, non i link che altri siti vi dedicano, non l’autorevolezza che si costruisce nel tempo. Non prevede in che posizione finirete, né studia la concorrenza sulle vostre parole chiave. È il controllo delle fondamenta: se sono storte, nemmeno il testo migliore rende; se sono a posto, avete tolto di mezzo gli ostacoli tecnici.',
         ]),
         lettura=('Come interpretare il punteggio SEO di Google', [
             'Da 90 in su le basi tecniche sono in ordine e potete concentrarvi su contenuti e reputazione. Tra 50 e 89 restano correzioni concrete — spesso un title mancante o una description duplicata — che si sistemano in fretta. Sotto 50 c’è qualcosa che ostacola l’indicizzazione: è la priorità, prima di ogni altra cosa. Leggete la lista degli avvisi dall’alto verso il basso: è già ordinata per impatto.',
             'Attenzione a due letture sbagliate. Un punteggio pieno non vuol dire «primi su Google»: significa solo che la pagina è tecnicamente leggibile, e il posizionamento arriva con contenuti e tempo. E un avviso su un tag secondario non è un’emergenza: distinguete i problemi che bloccano l’indicizzazione da quelli cosmetici, e partite dai primi.',
         ]),
         migliorare=dict(h2='Come migliorare il posizionamento on-page',
             intro='La SEO tecnica on-page è fatta di poche cose fatte bene, ripetute su ogni pagina che conta.',
             punti=[
                 ('Un title e una description su misura', 'Scrivete per ogni pagina un titolo unico e descrittivo e una meta description che invita al clic: sono la prima cosa che vede chi cerca.'),
                 ('Una gerarchia di titoli pulita', 'Un solo H1, poi H2 e H3 ordinati per argomento: aiutano Google e i lettori a capire la struttura della pagina in un colpo d’occhio.'),
                 ('Aggiungete i dati strutturati', 'Il markup schema.org in JSON-LD dice ai motori chi siete e cosa offrite, e vi rende idonei ai risultati arricchiti.'),
                 ('Curate link interni e URL', 'Collegate le pagine tra loro con testi di ancoraggio chiari e mantenete indirizzi brevi e leggibili: la struttura conta quanto il contenuto.'),
                 ('Tenete in ordine sitemap e robots', 'Una sitemap XML aggiornata e un robots.txt corretto guidano il crawler; se il sito è in più lingue, aggiungete i tag hreflang.'),
             ],
             links=[
                 ('Vogliamo sistemarla noi: scopri la SEO tecnica', '/servizi/seo-tecnica/'),
                 ('Approfondisci: i Core Web Vitals nel 2026', '/blog/core-web-vitals-2026/'),
             ]),
         cta=dict(heading='Vogliamo sistemare noi la SEO tecnica?',
                  testo='Audit completo, dati strutturati e Core Web Vitals a posto: PageSpeed 90+ garantito da contratto.',
                  buttons=[('Scopri la SEO tecnica', '/servizi/seo-tecnica/', None),
                           ('Verifica se il sito è pronto per l’AI', '/strumenti/sito-pronto-ai/', 'outline')])),
    dict(slug='check-gdpr', idx='/03', tipo='gdpr', titolo='Check GDPR e cookie',
         hero_titolo='Il vostro sito è a norma GDPR?',
         hero_sub='Controlliamo banner cookie, informative e tracker attivi prima del consenso: quattro verifiche per capire cosa manca. È una verifica indicativa, non una consulenza legale.',
         descrizione='Banner, informative e consensi: cosa manca per essere a norma.', has_demo=False,
         come_funziona=[
             ('Inserite l’indirizzo del sito', 'Leggiamo la home page dal nostro server, come farebbe un visitatore alla prima apertura.'),
             ('Quattro controlli automatici', 'Cerchiamo il cookie banner (CMP), i link a privacy e cookie policy, i tracker caricati prima del consenso e i domini esterni.'),
             ('Semaforo, non sentenza', 'Ogni punto è verde, giallo o rosso: segnaliamo i problemi evidenti, non un audit legale completo.'),
         ],
         faq=[
             ('È un parere legale?', 'No, ed è importante dirlo: è una verifica automatica indicativa, non una consulenza legale. Segnala i problemi tecnici evidenti; la conformità piena va valutata da un consulente privacy.'),
             ('Cosa vuol dire «tracker senza banner»?', 'Che nell’HTML iniziale della pagina troviamo strumenti di tracciamento (Google Analytics, Meta Pixel e simili) attivi prima che l’utente accetti. È il segnale rosso più frequente sui siti italiani.'),
             ('Perché il Garante è così severo sui cookie?', 'Perché il consenso deve essere libero, informato e documentabile: rifiutare deve essere facile quanto accettare, e nessun tracker pubblicitario può partire prima del sì.'),
         ],
         metodologia=('Cosa verifica davvero questo controllo cookie', [
             'A differenza dei test basati su Google, qui è il nostro server a leggere la home page del vostro sito, esattamente come la vedrebbe un visitatore alla prima apertura, prima di qualsiasi clic. Su quell’HTML facciamo quattro controlli automatici: cerchiamo il banner dei cookie (la CMP: Iubenda, Cookiebot, Complianz e simili), i collegamenti a privacy e cookie policy, gli strumenti di tracciamento che partono prima del consenso e i domini esterni che la pagina richiama.',
             'Diciamolo subito, perché conta: non è un parere legale. È una verifica tecnica indicativa, che intercetta i problemi evidenti — quelli che il Garante contesta più spesso — ma non sostituisce un consulente privacy. Non legge cosa accade dopo che l’utente accetta, non valuta i vostri registri dei consensi, non esamina le informative riga per riga. È un ottimo punto di partenza per capire dove intervenire, non un certificato di conformità.',
         ]),
         lettura=('Come leggere il semaforo di conformità', [
             'Ogni punto riceve un colore, e il colore va preso per quello che è. Verde: il segnale è presente e a posto. Giallo: qualcosa c’è ma va verificato a mano — per esempio una policy che esiste ma potrebbe essere incompleta. Rosso: manca un elemento importante o, peggio, ci sono tracker attivi senza un banner che li governi. Il quadro d’insieme conta più del singolo pallino.',
             'Il rosso più frequente sui siti italiani è «tracker senza banner»: Google Analytics o il Pixel di Meta che si attivano nell’HTML iniziale, prima del sì dell’utente. È anche l’errore che il Garante sanziona con più decisione. Un giallo, invece, di solito non è un’emergenza: spesso basta completare o aggiornare un’informativa già presente.',
         ]),
         migliorare=dict(h2='Come mettere a norma il consenso e i cookie',
             intro='La conformità pratica si costruisce con pochi accorgimenti, ma vanno rispettati tutti.',
             punti=[
                 ('Installate una CMP che blocca davvero', 'Un banner serio non deve solo comparire: deve impedire ai tracker di partire finché l’utente non ha accettato. È la differenza tra sembrare a norma ed esserlo.'),
                 ('Rendete il rifiuto facile quanto l’assenso', 'Il pulsante «Rifiuta» deve avere lo stesso peso di «Accetta», sulla stessa schermata: niente cookie wall, niente percorsi a ostacoli per dire di no.'),
                 ('Pubblicate informative complete', 'Privacy policy e cookie policy chiare, aggiornate e facili da trovare: devono dire cosa raccogliete, perché e con chi lo condividete.'),
                 ('Rendete il consenso documentabile', 'Conservate la prova di ogni consenso — quando, per cosa — così da poterla mostrare se richiesto: il sì deve essere libero, informato e tracciabile.'),
                 ('Caricate i tracker dopo il sì', 'Analytics, pixel e mappe di calore vanno attivati solo dopo l’accettazione, in modo condizionato: prima del consenso la pagina deve restare pulita.'),
             ],
             links=[
                 ('Lo includiamo in ogni sito aziendale che consegniamo', '/servizi/siti-aziendali/'),
                 ('Approfondisci: la checklist cookie 2026 del Garante', '/blog/cookie-banner-checklist-garante-2026/'),
             ]),
         cta=dict(heading='Vogliamo mettere il sito a norma?',
                  testo='Banner, informative e consensi conformi al Garante, inclusi in ogni sito aziendale che consegniamo.',
                  buttons=[('Scopri i siti aziendali', '/servizi/siti-aziendali/', None),
                           ('Richiedi un’analisi', '/#contatti', 'outline')])),
    dict(slug='roi-localizzazione', idx='/04', tipo='roi', titolo='ROI localizzazione',
         hero_titolo='Quanto rende tradurre il vostro sito',
         hero_sub='Una stima di quanto potreste guadagnare traducendo il sito in inglese o tedesco: bastano cinque numeri della vostra attività. Il calcolo resta sul vostro dispositivo. È una stima, non una promessa.',
         descrizione='Quanto rende tradurre il sito in inglese o tedesco.', has_demo=False,
         come_funziona=[
             ('Inserite i vostri numeri', 'Visite mensili, quota di pubblico estero, tasso di conversione, scontrino medio. Se non li avete precisi, partite dalle stime.'),
             ('Applichiamo il boost di localizzazione', 'Sul pubblico estero applichiamo un incremento prudente di conversione (+40%), dai dati CSA Research sull’acquisto in lingua madre.'),
             ('Leggete il ricavo potenziale', 'Il calcolatore mostra il ricavo aggiuntivo stimato al mese e all’anno. Cambiate i numeri e vedete subito come si muove.'),
         ],
         faq=[
             ('Da dove viene il «+40%»?', 'Dalle ricerche CSA Research: la larga maggioranza dei consumatori compra più volentieri, e più spesso, nella propria lingua. Il 40% è un valore prudente, che potete modificare.'),
             ('È una previsione garantita?', 'No: è una stima per ordini di grandezza, utile a capire se vale la pena approfondire. I risultati reali dipendono dal mercato, dall’offerta e dalla qualità della traduzione.'),
             ('Perché tradurre da madrelingua e non con un plugin?', 'Perché un cliente estero riconosce un testo automatico alla seconda riga — e con lui se ne va la fiducia. Nel gruppo Remarka la traduzione la fanno madrelingua, dal 2001.'),
         ],
         metodologia=('Come funziona davvero questa stima del ROI', [
             'Questo strumento non interroga alcun server e non guarda il vostro sito: è un calcolatore che gira interamente sul vostro dispositivo, e i numeri che inserite non lasciano il browser. Prende cinque dati della vostra attività — visite mensili, quota di pubblico estero, tasso di conversione, scontrino medio — e li combina con un incremento di conversione applicato alla sola fetta di visitatori stranieri.',
             'Quell’incremento, un prudente +40%, viene dalle ricerche CSA Research: la larga maggioranza delle persone compra più volentieri, e più spesso, nella propria lingua. È un valore di partenza, non una legge fisica: potete modificarlo. E qui sta anche il limite onesto dello strumento — è una stima per ordini di grandezza, non una previsione garantita. Non conosce il vostro mercato, la vostra offerta né la qualità della traduzione, che sono poi ciò che fa la differenza vera.',
         ]),
         lettura=('Come interpretare il ricavo potenziale stimato', [
             'Il risultato va letto come una forchetta, non come una cifra al centesimo. Serve a rispondere a una sola domanda: vale la pena approfondire la traduzione del sito, sì o no? Se il ricavo aggiuntivo stimato all’anno copre comodamente il costo di un progetto multilingue, il segnale è chiaro. Se è modesto, forse il vostro pubblico estero è ancora troppo piccolo perché l’investimento si ripaghi in fretta.',
             'Muovete i numeri e osservate come reagisce la stima: è lì che il calcolatore diventa utile. Alzando la quota di visitatori esteri o lo scontrino medio, il ricavo cresce in fretta, e questo vi dice quali leve pesano di più nel vostro caso. Ricordate che tutto parte dalle vostre cifre: se sono ottimistiche, lo sarà anche il risultato. Meglio partire da stime prudenti.',
         ]),
         migliorare=dict(h2='Come aumentare il rendimento della traduzione',
             intro='Tradurre un sito rende, ma solo se è fatto per vendere e non per figurare.',
             punti=[
                 ('Traducete da madrelingua, non con un plugin', 'Un cliente estero riconosce un testo automatico alla seconda riga, e con lui se ne va la fiducia. La traduzione professionale è ciò che trasforma la visita in ordine.'),
                 ('Localizzate, non solo tradurre', 'Adattate offerta, inviti all’azione, valuta e formati al mercato di arrivo: vendere in Germania non è tradurre le schede, è parlare come parla quel mercato.'),
                 ('Impostate la SEO internazionale', 'Ogni lingua ha bisogno dei suoi URL, dei tag hreflang e dei metadati dedicati, altrimenti Google non capisce a chi mostrare quale versione.'),
                 ('Partite dal mercato con più domanda', 'Non tutte le lingue rendono uguale: cominciate da dove i dati mostrano già interesse, poi allargate mercato per mercato.'),
                 ('Curate anche il dopo-vendita', 'Moduli, email di conferma e assistenza nella lingua del cliente: la fiducia si conferma dopo l’acquisto, non solo prima.'),
             ],
             links=[
                 ('Vogliamo tradurlo sul serio: scopri i siti multilingue', '/servizi/siti-multilingue/'),
                 ('Approfondisci: costi e tempi di un sito in quattro lingue', '/blog/sito-quattro-lingue-costi-tempi/'),
             ]),
         cta=dict(heading='Vogliamo tradurre il sito sul serio?',
                  testo='Traduzione professionale da madrelingua e SEO internazionale corretta dal primo giorno — non un plugin.',
                  buttons=[('Siti multilingue', '/servizi/siti-multilingue/', None),
                           ('Export Ready', '/servizi/export-ready/', 'outline')])),
    dict(slug='verifica-accessibilita', idx='/05', tipo='a11y', titolo='Verifica accessibilità',
         hero_titolo='Verifica accessibilità: il vostro sito è usabile da tutti?',
         hero_sub='Controlliamo con Google le barriere di accessibilità più comuni — contrasti, etichette, struttura. Dal 28 giugno 2025 l’European Accessibility Act rende l’accessibilità un obbligo per molti siti. Senza registrazione.',
         descrizione='Le barriere di accessibilità più comuni, misurate con Google.', has_demo=False,
         come_funziona=[
             ('Inserite l’indirizzo', 'La pagina da controllare: la home o una pagina di servizio, dove passano più utenti.'),
             ('Analisi Lighthouse', 'Usiamo la categoria Accessibilità di Lighthouse via API PageSpeed: contrasti, testi alternativi, etichette dei moduli, struttura dei titoli.'),
             ('Vedete le barriere da rimuovere', 'Punteggio 0–100 e la lista dei problemi rilevati, in italiano. Un controllo automatico copre parte dei criteri WCAG, non tutti.'),
         ],
         faq=[
             ('Cos’è l’European Accessibility Act?', 'Una direttiva europea (EAA) applicata in Italia dal 28 giugno 2025: molti siti di aziende che vendono a consumatori devono essere accessibili secondo lo standard WCAG 2.1 livello AA. È un obbligo, con alcune esenzioni per le microimprese.'),
             ('Questo test basta per essere conformi?', 'No: un controllo automatico intercetta una parte dei criteri WCAG. La conformità piena richiede anche verifica manuale — navigazione da tastiera, screen reader, contenuti. È un ottimo punto di partenza, non un certificato.'),
             ('Riguarda anche la mia azienda?', 'Se vendete beni o servizi a consumatori online (e-commerce, banche, trasporti, servizi), con ogni probabilità sì. Le microimprese che offrono servizi hanno esenzioni: meglio verificare caso per caso.'),
         ],
         metodologia=('Cosa controlla davvero questo test di accessibilità', [
             'Il motore è la categoria Accessibilità di Lighthouse, richiamata via API PageSpeed: gli stessi controlli automatici che Google mette a disposizione degli sviluppatori. In pochi secondi la pagina viene esaminata su decine di regole tecniche — contrasto tra testo e sfondo, testi alternativi delle immagini, etichette dei campi nei moduli, ordine dei titoli, uso corretto degli attributi ARIA — e ne esce un punteggio da 0 a 100 con l’elenco delle barriere rilevate.',
             'Serve chiarezza sui limiti, perché qui è facile illudersi. Un controllo automatico intercetta soltanto una parte dei criteri WCAG 2.1 AA: cattura ciò che una macchina sa misurare, non ciò che va provato da una persona. Non verifica la navigazione da tastiera, l’esperienza con uno screen reader, la chiarezza dei contenuti per chi ha difficoltà cognitive. È il primo gradino verso la conformità richiesta dall’European Accessibility Act, non il certificato finale.',
         ]),
         lettura=('Come leggere il punteggio e le barriere rilevate', [
             'Il numero da 0 a 100 dice quanto la pagina supera i controlli automatici: più è alto, meno ostacoli evidenti restano. Ma il punteggio conta meno dell’elenco che lo accompagna. Ogni voce è una barriera concreta per una persona reale — un contrasto troppo debole per chi ci vede poco, un pulsante senza etichetta per chi usa uno screen reader. Partite da quelle, non dal totale.',
             'Un avvertimento sui falsi sensi di sicurezza: anche un 100 pieno non significa «sito conforme». Vuol dire che avete superato i test che una macchina può fare, e sono circa un terzo dei problemi possibili. Il resto — tastiera, lettori di schermo, contenuti — si verifica a mano. Prendete quindi un punteggio alto come una buona base, non come un traguardo raggiunto.',
         ]),
         migliorare=dict(h2='Come rendere il sito accessibile a tutti',
             intro='Molte barriere cadono con correzioni semplici, che migliorano l’esperienza di chiunque, non solo di chi ha una disabilità.',
             punti=[
                 ('Aumentate il contrasto', 'Testo e sfondo devono avere un rapporto di contrasto di almeno 4,5:1: il grigio chiaro elegante sullo schermo del designer diventa illeggibile al sole o per chi ci vede poco.'),
                 ('Descrivete le immagini', 'Ogni immagine informativa ha bisogno di un testo alternativo che ne racconti il contenuto: è ciò che uno screen reader legge a chi non può vederla.'),
                 ('Etichettate i moduli', 'Ogni campo deve avere un’etichetta esplicita e collegata: «Nome», «Email», «Messaggio», non solo un testo grigio che sparisce appena si scrive.'),
                 ('Ordinate titoli e focus', 'Una gerarchia di titoli coerente e un percorso navigabile da tastiera, con il focus sempre visibile, rendono la pagina usabile anche senza mouse.'),
                 ('Non affidatevi solo al colore', 'Un errore segnalato solo in rosso è invisibile a chi non distingue i colori: affiancate sempre un’icona o un testo che spieghi cosa succede.'),
             ],
             links=[
                 ('Vogliamo sistemarle noi: l’accessibilità è inclusa nei siti aziendali', '/servizi/siti-aziendali/'),
             ]),
         cta=dict(heading='Vogliamo rendere il sito accessibile?',
                  testo='Verifichiamo le barriere una per una — automatiche e manuali — e le sistemiamo secondo lo standard WCAG 2.1 AA.',
                  buttons=[('Richiedi una verifica di accessibilità', '/#contatti', None),
                           ('Scopri i siti aziendali', '/servizi/siti-aziendali/', 'outline')])),
    dict(slug='sito-pronto-ai', idx='/06', tipo='ai', titolo='Sito pronto per l’AI',
         hero_titolo='Il vostro sito è pronto per l’AI?',
         hero_sub='Quando ChatGPT, Claude o Perplexity leggono il web, trovano il vostro sito? Controlliamo quattro segnali: llms.txt, accesso dei crawler AI, dati strutturati e sitemap. Senza registrazione.',
         descrizione='llms.txt, crawler AI, dati strutturati e sitemap: quattro segnali.', has_demo=False,
         come_funziona=[
             ('Inserite l’indirizzo del sito', 'Leggiamo dal nostro server alcuni file pubblici e l’HTML della home page.'),
             ('Quattro verifiche', 'Cerchiamo il file llms.txt, controlliamo se robots.txt lascia passare i crawler AI (GPTBot, ClaudeBot, PerplexityBot, Google-Extended), i dati strutturati JSON-LD e la sitemap.'),
             ('Punteggio N su 4', 'Un semaforo per ogni segnale e un punteggio complessivo, con le indicazioni su cosa aggiungere per farsi trovare e citare dai modelli.'),
         ],
         faq=[
             ('Cos’è il file llms.txt?', 'Una proposta di standard: un file di testo in Markdown che riassume ai modelli AI cosa contiene il sito e come citarlo, come fa robots.txt per i motori di ricerca. È giovane, ma sempre più diffuso.'),
             ('Conviene far entrare i crawler AI?', 'Dipende dagli obiettivi: bloccarli protegge i contenuti, ma vi esclude dalle risposte generate. Per la maggior parte delle aziende, essere citati da ChatGPT o Perplexity è visibilità in più.'),
             ('I dati strutturati servono ancora?', 'Sì, più che mai: i dati JSON-LD (schema.org) aiutano sia Google sia i modelli AI a capire chi siete, cosa offrite e a chi. Sono la base di ogni buona indicizzazione.'),
         ],
         metodologia=('Cosa verifica davvero questo controllo di prontezza AI', [
             'Come per il controllo GDPR, è il nostro server a leggere alcuni file pubblici del vostro sito e l’HTML della home, senza passare da Google. Facciamo quattro verifiche: cerchiamo il file llms.txt, controlliamo se il robots.txt lascia passare i crawler dei modelli (GPTBot di OpenAI, ClaudeBot, PerplexityBot, Google-Extended), rileviamo i dati strutturati JSON-LD nella pagina e la presenza di una sitemap. Ne esce un punteggio di prontezza su quattro.',
             'È utile sapere cosa il test non promette. Verifica che i segnali tecnici ci siano, non che ChatGPT o Perplexity vi citino davvero: quello dipende anche dalla qualità e dall’autorevolezza dei contenuti, che nessuno strumento misura in automatico. E poiché llms.txt è uno standard giovane, la sua assenza non è ancora un errore grave: è un’occasione in più di farsi leggere bene dalle macchine. Leggete il punteggio come una lista di opportunità, non come una bocciatura.',
         ]),
         lettura=('Come leggere il punteggio di prontezza su 4', [
             'Ogni segnale vale un punto e ha il suo semaforo. Quattro su quattro significa che il sito offre alle intelligenze artificiali tutti gli appigli per capirlo e citarlo. Due o tre su quattro è la situazione più comune: manca quasi sempre llms.txt, a volte i dati strutturati. Zero o uno su quattro merita attenzione, soprattutto se il robots.txt blocca i crawler AI: in quel caso restate fuori dalle risposte generate, magari senza averlo deciso.',
             'Una precisazione che evita allarmi inutili. Bloccare i crawler AI non è un difetto in sé: è una scelta legittima, se volete proteggere i contenuti. Il test lo segnala perché sappiate che quella porta è chiusa, non per dirvi che sbagliate. Per la maggior parte delle aziende, però, essere citati da un assistente AI è visibilità in più, non un rischio: vale la pena valutarlo con consapevolezza.',
         ]),
         migliorare=dict(h2='Come farsi trovare e citare dai modelli AI',
             intro='Prepararsi all’AI non richiede stravolgimenti: sono gli stessi segnali che aiutano anche Google, più qualche novità.',
             punti=[
                 ('Pubblicate un file llms.txt', 'Un semplice file di testo in Markdown, nella radice del sito, che riassume chi siete e cosa offrite: è la mappa che i modelli leggono volentieri.'),
                 ('Aprite le porte ai crawler giusti', 'Nel robots.txt consentite l’accesso a GPTBot, ClaudeBot, PerplexityBot e Google-Extended, se volete comparire nelle risposte generate.'),
                 ('Aggiungete i dati strutturati', 'Il markup JSON-LD schema.org dice in modo esplicito nome, sede, offerta e servizi: è la base che sia Google sia le AI usano per capirvi.'),
                 ('Tenete la sitemap aggiornata', 'Una sitemap XML completa aiuta i crawler a trovare tutte le pagine; assicuratevi che i contenuti siano testo leggibile, non solo immagini.'),
                 ('Scrivete fatti espliciti', 'Dichiarate con chiarezza cosa fate, dove e per chi: i modelli citano ciò che capiscono senza ambiguità, non ciò che devono indovinare.'),
             ],
             links=[
                 ('Lo prepariamo noi: fa parte della SEO tecnica', '/servizi/seo-tecnica/'),
             ]),
         cta=dict(heading='Vogliamo preparare il sito per l’AI?',
                  testo='Dati strutturati, file corretti e struttura leggibile dalle macchine: fa parte della SEO tecnica che consegniamo.',
                  buttons=[('Scopri la SEO tecnica', '/servizi/seo-tecnica/', None),
                           ('Analizza la SEO on-page', '/strumenti/analisi-seo/', 'outline')])),
    dict(slug='impatto-co2', idx='/07', tipo='co2', titolo='Impatto CO₂',
         hero_titolo='Impatto CO₂ del vostro sito web',
         hero_sub='Ogni visita al sito consuma energia e produce CO₂. Misuriamo il peso della vostra pagina e stimiamo le emissioni per visita e all’anno, con il modello Sustainable Web Design. Un sito leggero è anche un sito veloce.',
         descrizione='Quanta CO₂ produce ogni visita — e quanta all’anno.', has_demo=False,
         come_funziona=[
             ('Inserite l’indirizzo', 'La pagina da misurare: di solito la home, la più visitata.'),
             ('Pesiamo la pagina', 'Con l’API PageSpeed misuriamo i byte totali che il browser deve scaricare per mostrare la pagina.'),
             ('Stima delle emissioni', 'Applichiamo il modello Sustainable Web Design (co2.js) e otteniamo i grammi di CO₂e per visita, il confronto con la media del web e la stima annua.'),
         ],
         faq=[
             ('Come calcolate le emissioni?', 'Con il modello Sustainable Web Design della Green Web Foundation (libreria co2.js, Apache-2.0): dal peso della pagina all’energia consumata, fino ai grammi di CO₂e. È una stima con coefficienti medi mondiali.'),
             ('Perché un sito leggero inquina meno?', 'Perché ogni byte trasferito consuma energia — nel data center, nella rete, sul vostro dispositivo. Meno peso significa meno energia, meno emissioni e, come effetto collaterale, un sito più veloce.'),
             ('La stima annua da dove viene?', 'Moltiplichiamo le emissioni per visita per un traffico di riferimento di 10.000 visite al mese. Cambiando il traffico reale del vostro sito, cambia la stima proporzionalmente.'),
         ],
         metodologia=('Come stimiamo davvero le emissioni della pagina', [
             'Il calcolo parte da un dato concreto e misurabile: con l’API PageSpeed pesiamo tutti i byte che il browser deve scaricare per mostrare la vostra pagina. Su quel peso applichiamo il modello Sustainable Web Design della Green Web Foundation — le stesse formule della libreria open source co2.js — che traduce i byte trasferiti in energia consumata lungo la catena (data center, rete, dispositivo) e infine in grammi di CO₂ equivalente per visita.',
             'È una stima, ed è giusto trattarla come tale. Il modello usa coefficienti medi mondiali per l’intensità energetica e per il mix elettrico: non conosce l’energia reale del vostro hosting né il comportamento esatto di ogni visitatore. Non è una misura certificata di impronta ambientale, ma un ordine di grandezza affidabile e confrontabile. Il pregio è che si lega a un fatto tecnico — il peso — su cui potete davvero intervenire.',
         ]),
         lettura=('Come leggere i grammi di CO₂ per visita', [
             'Il numero chiave è la CO₂ equivalente per singola visita, che confrontiamo con la media del web, intorno agli 0,8 grammi. Sotto quella soglia siete tra i siti leggeri; sensibilmente sopra, la pagina è più pesante della media e c’è margine per alleggerirla. La stima annua moltiplica quel valore per un traffico di riferimento: cambiando le visite reali del vostro sito, l’impatto cresce o cala in proporzione.',
             'Il confronto conta più del valore assoluto. Pochi grammi per visita sembrano nulla, ma moltiplicati per decine di migliaia di visite al mese diventano una cifra concreta, e soprattutto sono lo specchio di una pagina pesante: quasi sempre chi inquina di più è anche chi carica più lentamente. Leggete quindi l’impatto come un secondo indicatore delle prestazioni, non solo come una questione ambientale.',
         ]),
         migliorare=dict(h2='Come ridurre l’impronta di carbonio del sito',
             intro='Ridurre le emissioni e velocizzare il sito sono la stessa cosa: entrambe passano dal tagliare peso inutile.',
             punti=[
                 ('Alleggerite le immagini', 'Le fotografie sono quasi sempre la voce più pesante: convertitele in WebP o AVIF con caricamento differito e taglierete gran parte dei byte, e quindi delle emissioni.'),
                 ('Riducete script e font', 'Ogni libreria di terze parti e ogni famiglia di caratteri in più è energia trasferita a ogni visita: tenete solo ciò che serve davvero.'),
                 ('Sfruttate cache e CDN', 'Una buona cache e una rete di distribuzione evitano di trasferire gli stessi contenuti mille volte: meno traffico ripetuto, meno consumo.'),
                 ('Scegliete un hosting verde', 'Un provider alimentato da energia rinnovabile abbassa l’intensità di carbonio di ogni byte servito: è la leva più semplice per un effetto immediato.'),
                 ('Preferite un design sobrio', 'Niente video in riproduzione automatica o animazioni pesanti dove non servono: un’estetica pulita consuma meno e, spesso, comunica meglio.'),
             ],
             links=[
                 ('Vogliamo alleggerirlo noi: scopri il restyling tecnico', '/servizi/restyling-migrazione/'),
                 ('Approfondisci: le 7 cause di un sito lento', '/blog/sito-lento-cause-costi/'),
             ]),
         cta=dict(heading='Vogliamo alleggerire il sito?',
                  testo='Immagini ottimizzate, base tecnica pulita, meno peso a parità di contenuti: meno CO₂ e PageSpeed 90+ da contratto.',
                  buttons=[('Restyling e migrazione', '/servizi/restyling-migrazione/', None),
                           ('Misura la velocità', '/strumenti/test-velocita/', 'outline')])),
]

# Городские лендинги. Правило из piano-contenuti-seo.md §2: максимум 6–8
# содержательных страниц, каждая с локальным кейсом и отзывами с гео-привязкой —
# никаких клонов с заменой топонима (doorway-риск). У milano есть офис (полный
# блок «Dove siamo»); остальные города обслуживаются из Милана — честный блок
# «Serviamo {città} da Milano» вместо выдуманного адреса.
CITIES = [
    dict(
        slug='milano', nome='Milano', eyebrow='Web agency Milano', progetti=14, dal='2023',
        sub='Siti progressivi per PMI di Milano e provincia: PageSpeed 90+ garantito da contratto, consegna a data fissa, prezzo chiuso. Il primo incontro, da voi o in studio, non si paga.',
        has_office=True,
        indirizzo='Via Andrea Solari 43, 20144 Milano (MI)', metro='M2 S. Agostino — 4 min a piedi',
        orari='Lun–Ven 9:00–18:00', telefono='+39 02 8736 5412',
        case_slug='studio-legale-fontana', case_url_label='studiolegalefontana.it',
        case_eyebrow='Un caso da Milano', case_title='Studio Legale Fontana, Milano',
        recensioni=[
            ('Preventivo chiaro, consegnato il giorno promesso. Il sito carica subito anche in cantiere, dove la rete è quella che è.', 'Marco T. — impresa edile, Sesto S. Giovanni'),
            ('Ci hanno mostrato i numeri del vecchio sito prima di parlare di soldi. Nessuno l’aveva mai fatto.', 'Elena R. — showroom ceramiche, Milano'),
            ('Versione tedesca impeccabile: i clienti di Monaco ordinano dal sito senza scriverci più per chiedere chiarimenti.', 'Giulia B. — torneria meccanica, Cinisello'),
        ],
        faq=[
            ('Quanto costa un sito web a Milano?', 'Le agenzie milanesi chiedono in media 2.500–8.000 € per un sito aziendale. I nostri prezzi sono pubblici: vetrina da € 1.900, aziendale da € 3.900, e-commerce da € 7.500 — chiusi nel preventivo, con PageSpeed 90+ e data di consegna scritti nel contratto.'),
            ('Lavorate solo su Milano città?', 'No: Milano e tutta la provincia, più Monza e Brianza. Il primo incontro non si paga, da voi o nel nostro studio in zona Solari.'),
            ('Serve incontrarsi di persona?', 'Non è obbligatorio: analisi, preventivo e avanzamento lavori passano da videochiamate e da un ambiente di prova online. Ma se siete a Milano, il caffè lo offriamo noi.'),
        ],
    ),
    dict(
        slug='monza', nome='Monza', eyebrow='MONZA E BRIANZA', progetti=8, dal='2023',
        sub='Siti progressivi per PMI di Monza e della Brianza: PageSpeed 90+ garantito da contratto, consegna a data fissa, prezzo chiuso. Il primo incontro, da voi in azienda, non si paga.',
        has_office=False,
        vicino='A 20 minuti dal nostro studio di Milano: sopralluoghi e incontri in azienda senza costi di trasferta, in tutta la provincia di Monza e Brianza.',
        case_slug='arredamenti-colombo', case_url_label='arredamenticolombo.it',
        case_eyebrow='Un caso dalla Brianza', case_title='Arredamenti Colombo, Lissone',
        recensioni=[
            ('Lo showroom non ha mai chiuso: il sito nuovo è andato online in una notte, con i redirect già pronti.', 'Paolo C. — arredamenti su misura, Lissone'),
            ('Il catalogo si apre anche dove il Wi-Fi non prende. I clienti lo sfogliano in showroom dal telefono.', 'Andrea M. — cucine componibili, Seregno'),
            ('Prezzo chiuso davvero: nessun extra a fine lavori, ed era tutto scritto nel preventivo.', 'Federica P. — studio dentistico, Monza'),
        ],
        faq=[
            ('Quanto costa un sito web a Monza?', 'Gli stessi prezzi pubblici che applichiamo ovunque: vetrina da € 1.900, aziendale da € 3.900, e-commerce da € 7.500 — prezzo chiuso nel preventivo, PageSpeed 90+ e data di consegna nel contratto.'),
            ('Venite in azienda in Brianza?', 'Sì: il primo incontro non si paga e lo facciamo volentieri da voi — Lissone, Seregno, Desio, Vimercate, tutta la provincia.'),
            ('Avete già lavorato con aziende della zona?', 'Sì: il caso più citato del nostro portfolio è proprio a Lissone — Arredamenti Colombo, da 34 a 96 di PageSpeed con +41% di richieste di preventivo.'),
        ],
    ),
    dict(
        slug='bergamo', nome='Bergamo', eyebrow='BERGAMO E PROVINCIA', progetti=6, dal='2024',
        sub='Siti progressivi per PMI di Bergamo e provincia: PageSpeed 90+ garantito da contratto, consegna a data fissa, prezzo chiuso. Versione in tedesco tradotta da madrelingua per chi lavora con l’estero.',
        has_office=False,
        vicino='Un’ora dal nostro studio di Milano: primo incontro in azienda senza costi, da Bergamo città alle valli. Per il resto: ambiente di prova online e avanzamento visibile ogni venerdì.',
        case_slug='tecnoidraulica', case_url_label='tecnoidraulica.it',
        case_eyebrow='Un caso da Bergamo', case_title='TecnoIdraulica, Bergamo',
        recensioni=[
            ('I clienti di Bressanone e Merano finalmente trovano tutto in tedesco. Le richieste sono triplicate.', 'Titolare — impianti idraulici, Bergamo'),
            ('Sito consegnato il giorno scritto nel contratto. Non ci credevamo, è successo.', 'Luca R. — carpenteria metallica, Dalmine'),
            ('Il modulo contatti ci avvisa su WhatsApp: rispondiamo ai preventivi prima dei concorrenti.', 'Sara V. — serramenti, Treviglio'),
        ],
        faq=[
            ('Quanto costa un sito web a Bergamo?', 'Prezzi pubblici, uguali ovunque: vetrina da € 1.900, aziendale da € 3.900, e-commerce da € 7.500 — chiusi nel preventivo, con PageSpeed 90+ e data di consegna nel contratto.'),
            ('Fate siti in tedesco per chi lavora con l’estero?', 'Sì, ed è la nostra specialità: le traduzioni le fanno madrelingua del gruppo Remarka (nel settore dal 2001), non un plugin. Il caso TecnoIdraulica è nato così.'),
            ('Il primo incontro è davvero gratuito?', 'Sì: veniamo noi in azienda, analizziamo il sito attuale e vi lasciamo un report scritto con le priorità. Il preventivo arriva entro 24 ore.'),
        ],
    ),
    dict(
        slug='brescia', nome='Brescia', eyebrow='BRESCIA E PROVINCIA', progetti=5, dal='2024',
        sub='Siti progressivi per le PMI manifatturiere di Brescia e provincia: PageSpeed 90+ garantito da contratto, prezzo chiuso, versione in tedesco o inglese tradotta da madrelingua per chi esporta.',
        has_office=False,
        vicino='Serviamo Brescia e provincia dal nostro studio di Milano: primo incontro in azienda senza costi di trasferta, poi ambiente di prova online e avanzamento visibile ogni venerdì.',
        case_slug='tecnoidraulica', case_url_label='tecnoidraulica.it',
        case_eyebrow='Un caso vicino: Bergamo', case_title='TecnoIdraulica, Bergamo',
        recensioni=[
            ('Catalogo tecnico di 400 codici, ora si apre in un secondo. I clienti tedeschi ordinano senza telefonare.', 'Titolare — minuterie metalliche, Lumezzane'),
            ('Ci hanno fatto vedere i numeri del sito vecchio prima di parlare di prezzo. Serietà rara.', 'Giorgio F. — officina meccanica, Brescia'),
            ('Preventivo chiuso e data fissa, come promesso. Il sito è online dal giorno concordato.', 'Anna T. — azienda vinicola, Franciacorta'),
        ],
        faq=[
            ('Quanto costa un sito web a Brescia?', 'Prezzi pubblici, uguali ovunque: vetrina da € 1.900, aziendale da € 3.900, e-commerce da € 7.500 — chiusi nel preventivo, con PageSpeed 90+ e data di consegna nel contratto.'),
            ('Lavorate con aziende manifatturiere ed esportatrici?', 'È il nostro cliente tipo: cataloghi tecnici veloci, dati strutturati per ogni prodotto e versioni in tedesco o inglese tradotte da madrelingua del gruppo Remarka.'),
            ('Come seguiamo i lavori se siete a Milano?', 'Ambiente di prova online dal primo giorno, avanzamento visibile ogni venerdì, un unico referente. Il primo incontro lo facciamo comunque da voi, gratuitamente.'),
        ],
    ),
    dict(
        slug='como', nome='Como', eyebrow='COMO E PROVINCIA', progetti=4, dal='2024',
        sub='Siti progressivi per le PMI di Como e del lago: PageSpeed 90+ garantito da contratto, prezzo chiuso, versioni in inglese e tedesco tradotte da madrelingua per chi lavora con ospiti e clienti esteri.',
        has_office=False,
        vicino='Mezz’ora dal nostro studio di Milano: primo incontro da voi senza costi, da Como a Cantù alla sponda del lago. Poi ambiente di prova online e un unico referente.',
        case_slug='cantina-serralta', case_url_label='cantinaserralta.it',
        case_eyebrow='Un caso simile: vendere all’estero', case_title='Cantina Serralta, Asti',
        recensioni=[
            ('Il sito in inglese e tedesco ha cambiato la stagione: gli ospiti prenotano direttamente, senza portali.', 'Chiara L. — casa vacanze, Menaggio'),
            ('Da tre secondi a meno di uno: le richieste dal modulo sono raddoppiate in due mesi.', 'Matteo B. — falegnameria, Cantù'),
            ('Tutto scritto nel preventivo, tutto rispettato. E il sito vola anche in riva al lago.', 'Paola G. — studio commercialista, Como'),
        ],
        faq=[
            ('Quanto costa un sito web a Como?', 'Prezzi pubblici, uguali ovunque: vetrina da € 1.900, aziendale da € 3.900, e-commerce da € 7.500 — chiusi nel preventivo, con PageSpeed 90+ e data di consegna nel contratto.'),
            ('Fate siti multilingue per il turismo?', 'Sì: inglese e tedesco tradotti da madrelingua del gruppo Remarka (non da un plugin), con SEO internazionale corretta — hreflang, metadati per mercato.'),
            ('Il primo incontro è gratuito anche fuori Como città?', 'Sì, in tutta la provincia: veniamo noi, analizziamo il sito attuale e vi lasciamo un report scritto. Preventivo chiuso entro 24 ore.'),
        ],
    ),
]

# Обратная совместимость: старый импорт CITY указывает на Милан.
CITY = CITIES[0]

# Флагман «Export Ready» (линия 2 концепции) и «Web App» (линия 3).
# Цены — ориентир из concept-sviluppo-studio.md §3, помечены владельцу
# на подтверждение перед запуском рекламы.
EXPORT_READY = dict(
    slug='export-ready',
    eyebrow='Servizio / Export Ready',
    hero_title='Il vostro sito funziona anche in tedesco. Misurato, garantito, firmato',
    hero_sub='Un sito web per l’export vero: il sito nella lingua del cliente e la sua versione estera sotto un unico contratto, con localizzazione da madrelingua, SEO internazionale e KPI per ogni mercato. Nel settore linguistico dal 2001.',
    hero_stat_value='4', hero_stat_label='Lingue con traduttori madrelingua interni: inglese, tedesco, francese, russo.',
    problema_heading='Il buco in cui l’export perde soldi',
    problema_testo='Chi esporta oggi sceglie tra una web agency (che gira le traduzioni a terzi o a un plugin) e un’agenzia di traduzioni (che non costruisce siti né fa SEO internazionale). La responsabilità si spezza sempre a metà — esattamente dove il cliente estero decide se comprare. Remarka è l’unica configurazione in cui ingegneria e localizzazione professionale vivono nella stessa azienda, sotto lo stesso contratto.',
    garanzie_heading='Un sito web per l’export, garantito nero su bianco',
    garanzie=[
        'Localizzazione solo da madrelingua: nomi e qualifiche dei traduttori nel contratto',
        'Glossario di terminologia del vostro settore: è un deliverable, resta a voi',
        'Checklist SEO internazionale firmata: hreflang, metadati e URL per ogni mercato, allegata al collaudo',
        'KPI mensili per ogni mercato, per 12 mesi: traffico, posizioni, richieste',
    ],
    formati=[
        ('One Market', 'a partire da € 12.000', 'Un mercato, una lingua: analisi del mercato target fatta da madrelingua, architettura multilingue, localizzazione completa, SEO internazionale, 12 mesi di KPI.'),
        ('Multi-Market', '€ 18.000–35.000', 'Più mercati in sequenza pianificata: stessa base tecnica, glossario condiviso, priorità dei mercati decisa sui dati, report comparativo mensile.'),
    ],
    processo=[
        ('01', 'Analisi del mercato target', 'Un madrelingua studia come i vostri clienti cercano nel loro paese: parole, concorrenti, prezzi.'),
        ('02', 'Architettura multilingue', 'URL, hreflang, x-default, metadati per mercato: la base tecnica che Google richiede.'),
        ('03', 'Localizzazione, non traduzione', 'Offerta, CTA e moduli adattati al mercato, glossario approvato con voi.'),
        ('04', 'Lancio e misurazione', 'QA su tre livelli (visivo, funzionale, SEO), poi 12 mesi di KPI mensili per mercato.'),
    ],
    faq=[
        ('Perché non basta un plugin di traduzione?', 'Un plugin traduce parole, non argomenti di vendita. Un cliente tedesco riconosce un testo automatico alla seconda riga — e con lui se ne va la fiducia. I nostri madrelingua sono nel contratto, con nome e qualifica.'),
        ('Avete davvero i traduttori in casa?', 'Sì: Studio Remarka fa parte del gruppo Remarka, nel settore linguistico dal 2001, con traduttori madrelingua interni per inglese, tedesco, francese e russo.'),
        ('Come misurate i risultati per mercato?', 'Ogni mercato ha il suo report mensile: posizioni sulle parole chiave locali, traffico organico, richieste dal modulo. Per 12 mesi, inclusi nel prezzo.'),
    ],
)

WEB_APP = dict(
    slug='web-app',
    eyebrow='Servizio / Web app su misura',
    hero_title='Quando un sito non basta: web app, aree clienti, configuratori',
    hero_sub='Sviluppo web app su misura: portali B2B, cabine clienti, configuratori di prodotto, integrazioni con CRM e gestionale. Costruiti dallo stesso team che sviluppa i prodotti digitali del gruppo Remarka.',
    hero_stat_value='3', hero_stat_label='Prodotti digitali interni in produzione: piattaforma AI, TMS, servizio documenti.',
    per_chi_heading='Sviluppo web app per chi ha un processo, non solo una vetrina',
    per_chi=[
        'Aziende che gestiscono ordini, listini o pratiche via email e vogliono un’area clienti.',
        'Produttori con prodotti configurabili: un configuratore vende mentre l’ufficio tecnico dorme.',
        'PMI che devono collegare sito, CRM e gestionale senza reinserire i dati a mano.',
    ],
    formati=[
        ('MVP Sprint', 'a partire da € 15.000', 'Perimetro chiuso, prezzo chiuso, data fissa: la prima versione funzionante del prodotto in 6–8 settimane, pronta per utenti reali.'),
        ('Product Build', 'da € 25.000', 'Sviluppo per iterazioni con backlog condiviso e rilasci regolari: per prodotti che crescono con il business.'),
    ],
    prove_heading='La prova: i nostri prodotti interni',
    prove_testo='Non solo per i clienti: il gruppo Remarka sviluppa e usa in produzione i propri prodotti digitali — una piattaforma di traduzione AI, un TMS per i progetti linguistici e un servizio di documenti standard. Li pubblichiamo come casi studio con metriche tecniche reali, marchiati «Product Lab».',
    faq=[
        ('Quanto costa una web app?', 'Il formato MVP Sprint parte da € 15.000 con perimetro, prezzo e data chiusi nel contratto. Progetti a iterazioni partono da € 25.000. Il preventivo resta chiuso: quello che firmate è quello che pagate.'),
        ('Meglio una web app o un’app nativa?', 'Per la maggior parte delle PMI, una web app (o PWA) costa una frazione di un’app nativa, non passa dagli store e si aggiorna in un rilascio. L’app nativa serve solo per hardware specifico o notifiche avanzate.'),
        ('Chi mantiene il prodotto dopo il lancio?', 'Dodici mesi di assistenza inclusi, come per i siti. Dopo, canone facoltativo o consegna completa: codice e documentazione sono vostri dal primo giorno.'),
    ],
)

BLOG_POSTS = [
    dict(slug='sito-quattro-lingue-costi-tempi', data='05 MAG 2026',
         titolo='Un sito in quattro lingue: costi, tempi e gli errori da evitare',
         estratto='Quando la traduzione automatica basta e quando vi costa clienti. Con i prezzi reali per lingua e un caso di export in Germania.',
         corpo="La traduzione automatica basta per un menu o un orario di apertura. Non basta per una scheda prodotto tecnica o una pagina di vendita, dove un errore di registro costa un cliente prima ancora che scriva. In questo articolo spieghiamo quando conviene la traduzione automatica, quando serve un madrelingua, e cosa cambia davvero nei costi e nei tempi per lingua, con un caso reale di export verso la Germania."),
    dict(slug='cookie-banner-checklist-garante-2026', data='08 APR 2026',
         titolo='Cookie banner a norma: la checklist 2026 del Garante',
         estratto='Rifiuta equivalente ad accetta, niente cookie wall, consenso documentabile. Cosa controllare sul vostro sito, punto per punto.',
         corpo='Il Garante Privacy richiede che il pulsante «Rifiuta» abbia lo stesso peso visivo del pulsante «Accetta» in un cookie banner, e che il consenso sia documentabile nel tempo. Sono regole semplici, ma ignorate dalla maggior parte dei siti italiani che analizziamo. Ecco la checklist punto per punto che usiamo per verificare un sito, e come costruiamo i nostri banner per essere a norma fin dal primo giorno.'),
    dict(slug='migrare-wordpress-senza-perdere-seo', data='17 MAR 2026',
         titolo='Migrare da WordPress senza perdere le posizioni su Google',
         estratto='Redirect, struttura degli URL e cosa succede nelle prime sei settimane. Il protocollo che usiamo su ogni migrazione.',
         corpo='Ogni migrazione tecnica comporta il rischio di perdere anni di posizionamento organico. In questo articolo spieghiamo il protocollo di audit, mappatura URL e redirect 301 che applichiamo prima di ogni migrazione da WordPress, cosa monitoriamo nelle prime sei settimane dopo il cambio, e un caso reale in cui il posizionamento è rimasto invariato.'),
    dict(slug='pwa-per-pmi-quando-app-non-serve', data='24 FEB 2026',
         titolo="PWA per le PMI: quando l’app non serve",
         estratto="Un sito progressivo si installa, funziona offline e costa un quinto di un’app nativa. I tre casi in cui conviene davvero.",
         corpo="Sviluppare un’app nativa costa in media 15.000–30.000 euro e richiede manutenzione separata per iOS e Android. Un sito progressivo (PWA) offre installabilità, notifiche e funzionamento offline a una frazione del costo, senza revisione degli store. In questo articolo i tre casi concreti in cui una PWA conviene davvero a una PMI italiana, e i due in cui serve ancora un’app nativa."),
    dict(slug='quanto-costa-sito-aziendale-italia', data='03 FEB 2026',
         titolo='Quanto costa un sito aziendale in Italia: i prezzi veri',
         estratto='Da 800 a 50.000 euro: cosa cambia davvero tra le fasce e le domande da fare prima di firmare qualunque preventivo.',
         corpo="Il mercato dei siti web in Italia è frammentato e poco trasparente: si va dagli 800 euro dei costruttori fai-da-te ai 50.000 euro delle grandi agenzie. In questo articolo mappiamo onestamente cosa si compra a ogni fascia di prezzo, incluso il nostro, e le domande da fare prima di firmare qualunque preventivo."),
    dict(slug='core-web-vitals-2026', data='12 GEN 2026',
         titolo='Core Web Vitals nel 2026: cosa misura davvero Google',
         estratto='LCP, INP e CLS spiegati con esempi di negozi e officine, non di startup. E perché il punteggio desktop non conta quasi nulla.',
         corpo="LCP, INP e CLS sono le tre metriche che Google usa per valutare l’esperienza utente di un sito, e per decidere chi mostrare per primo nei risultati di ricerca mobile. In questo articolo le spieghiamo senza gergo tecnico, con esempi reali di negozi e officine — non di startup — e perché il punteggio desktop, su cui si concentrano ancora molte agenzie, conta ormai quasi nulla."),

    # ---- Mese 1 del piano contenuti (piano-contenuti-seo.md §4.3) ----
    dict(slug='quanto-costa-ecommerce-italia', data='13 LUG 2026',
         titolo='Quanto costa un e-commerce in Italia nel 2026: le cifre vere',
         estratto='Dai 6.000 ai 25.000 euro e oltre: cosa cambia davvero tra le fasce, quali costi ricorrenti nessuno mette nel preventivo, e le domande da fare prima di firmare.',
         corpo="«Quanto costa un e-commerce?» è la domanda con cui inizia quasi ogni nostra prima telefonata. La risposta onesta è una forchetta larga — sul mercato italiano da 6.000 a 25.000 euro e oltre — perché due negozi online con lo stesso numero di prodotti possono nascondere complessità completamente diverse. In questo articolo mettiamo in fila le cifre reali del mercato 2026, i costi che i preventivi tacciono e i tre fattori che spostano davvero il prezzo.",
         cta=('Vedi il nostro listino e-commerce, prezzi chiusi', '/prezzi/'),
         sezioni=[
             dict(titolo='Le fasce di prezzo del mercato italiano',
                  paragrafi=[
                      "I listini pubblici delle agenzie italiane nel 2026 raccontano un mercato su tre fasce. Sotto i 3.000 euro si trovano negozi montati su template con configurazione minima: funzionano finché non serve personalizzare il checkout o collegare il gestionale. La fascia centrale — 6.000–15.000 euro — copre un e-commerce professionale su misura: catalogo strutturato, pagamenti multipli, SEO tecnica delle pagine prodotto. Sopra i 15.000 si va verso cataloghi complessi, integrazioni con ERP e logistica, multi-lingua e multi-valuta.",
                      "Il nostro listino sta nella fascia centrale — € 7.500–14.000, prezzo chiuso nel preventivo — con una differenza contrattuale: PageSpeed 90+ garantito per iscritto e data di consegna con penale. Sono le due voci che nelle offerte concorrenti non troverete quasi mai nero su bianco.",
                  ]),
             dict(titolo='I costi che i preventivi non dicono',
                  paragrafi=[
                      "Il prezzo di costruzione è metà della storia. Un e-commerce vivo costa ogni anno: hosting adeguato ai picchi, aggiornamenti di sicurezza, commissioni sui pagamenti (tipicamente 1,5–3% a transazione), fatturazione elettronica, e la manutenzione del catalogo. Sul mercato la manutenzione professionale viaggia tra i 500 e i 2.000 euro l’anno: chiedete sempre cosa è incluso e per quanto tempo.",
                      "Nel nostro caso i primi 12 mesi di assistenza, aggiornamenti e misurazioni mensili sono inclusi nel prezzo di costruzione. Dopo, il canone è facoltativo — oppure il negozio resta a voi così com’è: codice e dati sono vostri dal primo giorno.",
                  ]),
             dict(titolo='I tre fattori che spostano il prezzo',
                  lista=[
                      'Catalogo: non quanti prodotti avete, ma quante varianti, listini e regole di prezzo (B2B vs B2C) il negozio deve gestire.',
                      'Integrazioni: gestionale, corrieri, magazzino esterno. Ogni sistema collegato è lavoro di sviluppo e di test, non una casella da spuntare.',
                      'Lingue e mercati: vendere in Germania non è tradurre le schede — è IVA, spedizioni, resi e testi che un madrelingua deve adattare al mercato.',
                  ],
                  paragrafi=[
                      "Un caso concreto dal nostro registro consegne: per Cantina Serralta (vini, Asti) il catalogo tradotto in tre lingue con checkout in un solo passaggio ha portato +63% di vendite dirette in un anno — e il costo del progetto si è ripagato prima della seconda vendemmia.",
                  ]),
             dict(titolo='Le domande da fare prima di firmare',
                  lista=[
                      'Il prezzo è chiuso o «indicativo»? Cosa succede se emergono lavori aggiuntivi?',
                      'La data di consegna è nel contratto? Con quale penale?',
                      'Chi possiede dominio, codice e dati dei clienti dopo la consegna?',
                      'La fatturazione elettronica via SDI è inclusa o è un modulo a parte?',
                      'Quanto carica il sito su mobile — e chi lo garantisce, per iscritto?',
                  ]),
         ]),
    dict(slug='sito-lento-cause-costi', data='13 LUG 2026',
         titolo='Sito lento: le 7 cause reali (e quanto costa sistemarle)',
         estratto='Perché un sito carica in 5 secondi nel 2026, quali interventi costano poco e rendono molto, e quando invece conviene rifare la base tecnica.',
         corpo="Quattro secondi di caricamento su mobile sembrano un dettaglio tecnico. Non lo sono: sono il motivo per cui le campagne portano visite che se ne vanno prima di vedere la prima riga. Dopo decine di audit su siti di PMI italiane, le cause della lentezza sono quasi sempre le stesse sette — e non tutte costano care da sistemare. Eccole, in ordine di frequenza, con l’ordine di grandezza dell’intervento.",
         cta=('Misura il tuo sito adesso — test gratuito', '/strumenti/test-velocita/'),
         sezioni=[
             dict(titolo='Le sette cause, dalla più frequente',
                  lista=[
                      'Immagini non ottimizzate: fotografie da 3–8 MB caricate così come escono dal telefono. È la causa №1 e la più economica da correggere.',
                      'Hosting inadeguato: server condivisi sovraffollati che rispondono in 1–2 secondi prima ancora di iniziare a caricare la pagina.',
                      'Tema o template sovraccarico: page builder che caricano 2 MB di codice per mostrare tre colonne di testo.',
                      'Plugin accumulati negli anni: ogni plugin attivo aggiunge codice, richieste e rischi di sicurezza — ne abbiamo contati fino a 60 su un solo sito.',
                      'Font e script esterni: sei famiglie di caratteri e dieci servizi di tracciamento che bloccano la prima visualizzazione.',
                      'Nessuna cache configurata: il server ricostruisce da zero ogni pagina, per ogni visitatore, ogni volta.',
                      'Base tecnica vecchia: versioni PHP obsolete e database mai ottimizzati — qui il singolo intervento non basta più.',
                  ]),
             dict(titolo='Cosa costa poco e rende molto',
                  paragrafi=[
                      "Le prime due cause — immagini e hosting — si risolvono spesso in giornata e da sole possono dimezzare i tempi di caricamento. La compressione moderna (AVIF/WebP con caricamento progressivo) taglia il peso delle fotografie dell’80% a parità di qualità visibile: sul restyling di Arredamenti Colombo ha valso −82% di peso e un punteggio PageSpeed passato da 34 a 96.",
                      "Cache e pulizia dei plugin sono il secondo gradino: mezza giornata di lavoro, risultati misurabili subito. Il punto è misurare prima e dopo — non «il sito sembra più veloce», ma un numero documentato.",
                  ]),
             dict(titolo='Quando il restyling tecnico conviene davvero',
                  paragrafi=[
                      "Se il vostro sito somma le cause 3, 4 e 7 — tema pesante, plugin stratificati, base vecchia — ottimizzare pezzo per pezzo è come cambiare le gomme a un motore fuso: ogni intervento costa e il risultato resta mediocre. In questi casi il restyling tecnico (stessi contenuti, base nuova, redirect 301 per non perdere il posizionamento) parte da € 2.900 e porta il sito sopra i 90 di PageSpeed — garantiti da contratto, non promessi.",
                      "Il primo passo è gratuito in entrambi i casi: misurate il sito con il nostro test di velocità, oppure chiedete l’analisi completa — un report scritto con le cause, le priorità e un preventivo chiuso.",
                  ]),
         ]),
]
